stages:
  split:
    cmd: python split.py texts.csv texts-train.csv texts-test.csv
    deps:
    - split.py
    - texts.csv
    params:
    - prepare.combine.layers
    - prepare.combine.max_depth
    - prepare.combine.ngrams
    - prepare.combine.num_est
    - prepare.combine.passes
    - prepare.combine.weight_factor
    - prepare.concurrent.dense
    - prepare.concurrent.drop
    - prepare.concurrent.max_depth
    - prepare.concurrent.split
    - prepare.concurrent.threads
    - prepare.concurrent.weight_factor
    - prepare.dev.batch_size
    - prepare.dev.columns
    - prepare.dev.epochs
    - prepare.dev.min_features
    - prepare.dev.ngrams
    - prepare.dev.seed
    - prepare.dev.split
    - prepare.model.estimators
    - prepare.model.features
    - prepare.model.min_split
    - prepare.model.num_est
    - prepare.model.split
    - prepare.other.columns
    - prepare.other.dense
    - prepare.other.max_depth
    - prepare.other.max_features
    - prepare.other.ngrams
    - prepare.other.num_est
    - prepare.other.split
    - prepare.preprocessing.batch_size
    - prepare.preprocessing.drop
    - prepare.preprocessing.max_depth
    - prepare.preprocessing.min_features
    - prepare.preprocessing.seed
    - prepare.preprocessing.split
    - prepare.preprocessing.weight_factor
    - prepare.test.min_split
    - prepare.test.passes
    - prepare.test.threads
    - prepare.test.weight_factor
    outs:
    - texts-test.csv
    - texts-train.csv
  featurize:
    cmd: python featurize.py texts-train.csv texts-train-feats.csv
    deps:
    - featurize.py
    - texts-train.csv
    params:
    - featurize.combine.columns
    - featurize.combine.estimators
    - featurize.combine.features
    - featurize.combine.min_split
    - featurize.combine.tags
    - featurize.combine.threads
    - featurize.combine.trees
    - featurize.combine.weight_factor
    - featurize.concurrent.max_features
    - featurize.concurrent.num_est
    - featurize.concurrent.seed
    - featurize.dev.num_est
    - featurize.dev.sample
    - featurize.model.batch_size
    - featurize.model.columns
    - featurize.model.folds
    - featurize.model.passes
    - featurize.model.random_state
    - featurize.model.split
    - featurize.model.tags
    - featurize.other.batch_size
    - featurize.other.drop
    - featurize.other.estimators
    - featurize.other.passes
    - featurize.other.random_state
    - featurize.other.trees
    - featurize.preprocessing.columns
    - featurize.preprocessing.epochs
    - featurize.preprocessing.estimators
    - featurize.preprocessing.max_features
    - featurize.preprocessing.min_features
    - featurize.preprocessing.trees
    - featurize.test.min_split
    - featurize.test.trees
    outs:
    - texts-train-feats.csv
  train:
    cmd: python train.py texts-train-feats.csv model.json
    deps:
    - texts-train-feats.csv
    - train.py
    params:
    - settings.combine.sample
    - settings.concurrent.drop
    - settings.concurrent.min_features
    - settings.concurrent.ngrams
    - settings.concurrent.random_state
    - settings.concurrent.sample
    - settings.concurrent.seed
    - settings.dev.batch_size
    - settings.dev.folds
    - settings.dev.learning_rate
    - settings.dev.ngrams
    - settings.dev.num_est
    - settings.dev.random_state
    - settings.dev.tags
    - settings.dev.threads
    - settings.model.dense
    - settings.model.estimators
    - settings.other.columns
    - settings.other.estimators
    - settings.other.features
    - settings.other.folds
    - settings.other.min_features
    - settings.other.random_state
    - settings.other.tags
    - settings.other.weight_factor
    - settings.preprocessing.drop
    - settings.preprocessing.estimators
    - settings.preprocessing.max_features
    - settings.preprocessing.min_split
    - settings.preprocessing.sample
    - settings.preprocessing.split
    - settings.preprocessing.threads
    - settings.test.columns
    - settings.test.dense
    - settings.test.min_features
    - settings.test.ngrams
    - settings.test.num_est
    - settings.test.random_state
    - tagging.combine.columns
    - tagging.combine.max_depth
    - tagging.combine.split
    - tagging.concurrent.dense
    - tagging.concurrent.max_depth
    - tagging.concurrent.num_est
    - tagging.concurrent.passes
    - tagging.concurrent.threads
    - tagging.concurrent.trees
    - tagging.dev.columns
    - tagging.dev.epochs
    - tagging.dev.features
    - tagging.dev.folds
    - tagging.dev.learning_rate
    - tagging.dev.max_depth
    - tagging.dev.random_state
    - tagging.dev.tags
    - tagging.model.batch_size
    - tagging.model.features
    - tagging.model.layers
    - tagging.model.min_features
    - tagging.model.min_split
    - tagging.model.seed
    - tagging.model.split
    - tagging.model.weight_factor
    - tagging.other.columns
    - tagging.other.dense
    - tagging.other.epochs
    - tagging.other.features
    - tagging.other.max_features
    - tagging.other.random_state
    - tagging.other.threads
    - tagging.preprocessing.dense
    - tagging.preprocessing.features
    - tagging.preprocessing.ngrams
    - tagging.preprocessing.sample
    - tagging.test.drop
    - tagging.test.folds
    - tagging.test.max_depth
    - tagging.test.max_features
    - tagging.test.min_split
    - tagging.test.split
    - tagging.test.trees
    - train.combine.folds
    - train.combine.layers
    - train.combine.ngrams
    - train.concurrent.batch_size
    - train.concurrent.estimators
    - train.concurrent.layers
    - train.concurrent.sample
    - train.concurrent.split
    - train.concurrent.trees
    - train.dev.features
    - train.dev.learning_rate
    - train.dev.min_split
    - train.dev.seed
    - train.model.columns
    - train.model.features
    - train.model.learning_rate
    - train.model.random_state
    - train.model.split
    - train.model.threads
    - train.model.weight_factor
    - train.other.passes
    - train.other.seed
    - train.preprocessing.drop
    - train.preprocessing.learning_rate
    - train.test.split
    - train.test.trees
    - validation.combine.features
    - validation.combine.learning_rate
    - validation.combine.min_features
    - validation.combine.passes
    - validation.concurrent.drop
    - validation.concurrent.epochs
    - validation.concurrent.layers
    - validation.concurrent.random_state
    - validation.concurrent.weight_factor
    - validation.dev.features
    - validation.dev.folds
    - validation.dev.min_split
    - validation.dev.split
    - validation.dev.trees
    - validation.model.max_depth
    - validation.model.min_split
    - validation.model.ngrams
    - validation.other.epochs
    - validation.other.learning_rate
    - validation.other.num_est
    - validation.other.tags
    - validation.preprocessing.columns
    - validation.preprocessing.layers
    - validation.preprocessing.passes
    - validation.preprocessing.split
    - validation.preprocessing.trees
    - validation.preprocessing.weight_factor
    - validation.test.dense
    - validation.test.passes
    - validation.test.tags
    - validation.test.threads
    - validation.test.weight_factor
    - variables.combine.batch_size
    - variables.combine.estimators
    - variables.combine.features
    - variables.combine.sample
    - variables.concurrent.columns
    - variables.concurrent.folds
    - variables.concurrent.min_features
    - variables.concurrent.split
    - variables.concurrent.threads
    - variables.dev.columns
    - variables.dev.max_features
    - variables.dev.min_features
    - variables.dev.split
    - variables.dev.threads
    - variables.dev.weight_factor
    - variables.model.columns
    - variables.model.folds
    - variables.model.max_features
    - variables.other.batch_size
    - variables.other.features
    - variables.other.max_features
    - variables.other.sample
    - variables.other.threads
    - variables.other.weight_factor
    - variables.preprocessing.dense
    - variables.preprocessing.estimators
    - variables.preprocessing.ngrams
    - variables.test.epochs
    - variables.test.features
    - variables.test.min_split
    - variables.test.random_state
    - variables.test.weight_factor
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json texts-test.csv
    deps:
    - evaluate.py
    - model.json
    - texts-test.csv
    metrics:
    - metrics.json:
        cache: false
