featurize:
  preprocessing:
    estimators: 49
    epochs: 69
    trees: 45
    columns: 86
    min_features: 2778
    max_features: 3448
  test:
    trees: 20
    min_split: 57
  model:
    random_state: 552259670
    batch_size: 943
    tags: 132
    passes: 40
    folds: 10
    split: 0.10847
    columns: 19
  combine:
    weight_factor: 0.07787
    features: 2659
    min_split: 62
    trees: 40
    estimators: 181
    columns: 50
    tags: 11
    threads: 17
  other:
    trees: 67
    random_state: 146465105
    passes: 66
    estimators: 53
    batch_size: 507
    drop: 0.22254
  dev:
    num_est: 245
    sample: 0.25729
  concurrent:
    seed: 23921690
    num_est: 190
    max_features: 3894
validation:
  concurrent:
    layers: 2
    weight_factor: 0.3
    drop: 0.3
    epochs: 25
    random_state: 781283702
  dev:
    features: 4410
    trees: 54
    min_split: 80
    split: 0.56779
    folds: 6
  combine:
    min_features: 312
    passes: 94
    features: 2917
    learning_rate: 0.15
  test:
    tags: 49
    weight_factor: 0.2
    threads: 30
    dense: 282
    passes: 148
  preprocessing:
    split: 0.09131
    columns: 81
    passes: 118
    weight_factor: 0.1
    layers: 3
    trees: 49
  other:
    tags: 7
    num_est: 23
    epochs: 15
    learning_rate: 0.08
  model:
    max_depth: 35
    ngrams: 4
    min_split: 28
settings:
  dev:
    ngrams: 2
    tags: 56
    threads: 3
    batch_size: 32
    num_est: 25
    folds: 2
    random_state: 458432672
    learning_rate: 0.04
  other:
    folds: 6
    columns: 15
    min_features: 5157
    weight_factor: 0.15405
    features: 1593
    random_state: 282000000
    estimators: 183
    tags: 35
  test:
    random_state: 576000000
    columns: 42
    num_est: 125
    ngrams: 2
    min_features: 2047
    dense: 200
  concurrent:
    min_features: 1600
    random_state: 853000000
    sample: 0.74701
    ngrams: 2
    drop: 0.1
    seed: 911991523
  preprocessing:
    sample: 0.26052
    drop: 0.08704
    threads: 17
    split: 0.3
    estimators: 204
    min_split: 80
    max_features: 4950
  combine:
    sample: 0.5
  model:
    dense: 236
    estimators: 90
prepare:
  concurrent:
    threads: 6
    split: 0.08187
    max_depth: 8
    drop: 0.47022
    dense: 500
    weight_factor: 0.07933
  preprocessing:
    min_features: 2871
    drop: 0.2
    batch_size: 70
    weight_factor: 0.24117
    split: 0.50709
    seed: 753678833
    max_depth: 4
  model:
    estimators: 163
    num_est: 200
    split: 0.40289
    features: 5482
    min_split: 51
  combine:
    weight_factor: 0.12319
    passes: 100
    ngrams: 4
    layers: 3
    num_est: 124
    max_depth: 12
  test:
    weight_factor: 0.33479
    passes: 3
    min_split: 51
    threads: 13
  other:
    max_depth: 20
    split: 0.36589
    max_features: 4900
    ngrams: 5
    num_est: 222
    columns: 71
    dense: 79
  dev:
    ngrams: 3
    batch_size: 644
    min_features: 1656
    epochs: 34
    split: 0.48939
    columns: 52
    seed: 239484085
tagging:
  model:
    weight_factor: 0.24002
    seed: 448206000
    split: 0.5
    min_features: 1300
    batch_size: 624
    min_split: 80
    layers: 2
    features: 3420
  combine:
    max_depth: 32
    split: 0.2
    columns: 23
  other:
    max_features: 4200
    columns: 36
    epochs: 70
    threads: 13
    features: 644
    random_state: 856451491
    dense: 400
  test:
    trees: 75
    max_depth: 16
    min_split: 80
    drop: 0.1
    folds: 6
    split: 0.2
    max_features: 4932
  dev:
    columns: 48
    features: 3300
    max_depth: 32
    random_state: 454000000
    tags: 119
    epochs: 5
    learning_rate: 0.01
    folds: 9
  concurrent:
    trees: 42
    num_est: 125
    passes: 40
    max_depth: 9
    dense: 300
    threads: 18
  preprocessing:
    ngrams: 2
    dense: 100
    sample: 0.75
    features: 4170
variables:
  concurrent:
    min_features: 2399
    split: 0.4
    threads: 18
    columns: 21
    folds: 3
  combine:
    features: 2676
    batch_size: 464
    sample: 0.86293
    estimators: 81
  preprocessing:
    estimators: 186
    dense: 232
    ngrams: 6
  other:
    batch_size: 288
    weight_factor: 0.1
    max_features: 3427
    sample: 0.25
    threads: 0
    features: 4420
  dev:
    max_features: 2650
    weight_factor: 0.23672
    min_features: 4250
    split: 0.1
    threads: 10
    columns: 42
  test:
    min_split: 48
    weight_factor: 0.07915
    features: 4820
    random_state: 18229596
    epochs: 65
  model:
    folds: 6
    max_features: 2912
    columns: 14
train:
  preprocessing:
    drop: 0.1652
    learning_rate: 0.10494
  model:
    random_state: 175000000
    features: 1060
    threads: 9
    weight_factor: 0.3
    split: 0.2
    columns: 66
    learning_rate: 0.08
  test:
    trees: 75
    split: 0.3
  dev:
    min_split: 64
    learning_rate: 0.14293
    seed: 853642358
    features: 4802
  concurrent:
    layers: 2
    estimators: 108
    batch_size: 708
    sample: 0.75
    split: 0.30522
    trees: 3
  other:
    passes: 102
    seed: 899860000
  combine:
    ngrams: 4
    folds: 9
    layers: 4
