stages:
  split:
    cmd: python split.py texts.csv texts-train.csv texts-test.csv
    deps:
    - split.py
    - texts.csv
    params:
    - prepare.combine.dense
    - prepare.combine.features
    - prepare.combine.folds
    - prepare.combine.learning_rate
    - prepare.combine.split
    - prepare.combine.weight_factor
    - prepare.diff.epochs
    - prepare.diff.estimators
    - prepare.long.dense
    - prepare.long.epochs
    - prepare.long.features
    - prepare.long.max_depth
    - prepare.long.sample
    - prepare.long.trees
    - prepare.long.weight_factor
    - prepare.other.random_state
    - prepare.other.split
    - prepare.other.trees
    - prepare.preset.dense
    - prepare.preset.estimators
    - prepare.preset.folds
    - prepare.preset.learning_rate
    - prepare.preset.max_depth
    - prepare.preset.min_features
    - prepare.preset.seed
    - prepare.requests.epochs
    - prepare.requests.passes
    - prepare.requests.random_state
    - prepare.requests.weight_factor
    - prepare.test.columns
    - prepare.test.features
    - prepare.test.num_est
    - prepare.test.sample
    - prepare.test.trees
    outs:
    - texts-test.csv
    - texts-train.csv
  featurize:
    cmd: python featurize.py texts-train.csv texts-train-feats.csv
    deps:
    - featurize.py
    - texts-train.csv
    outs:
    - texts-train-feats.csv
  train:
    cmd: python train.py texts-train-feats.csv model.json
    deps:
    - texts-train-feats.csv
    - train.py
    params:
    - concurrent.combine.epochs
    - concurrent.diff.columns
    - concurrent.diff.max_depth
    - concurrent.diff.sample
    - concurrent.diff.seed
    - concurrent.diff.tags
    - concurrent.diff.trees
    - concurrent.long.batch_size
    - concurrent.long.dense
    - concurrent.long.folds
    - concurrent.long.max_depth
    - concurrent.long.min_split
    - concurrent.long.ngrams
    - concurrent.long.num_est
    - concurrent.long.random_state
    - concurrent.long.sample
    - concurrent.long.split
    - concurrent.other.max_depth
    - concurrent.other.tags
    - concurrent.preset.features
    - concurrent.preset.layers
    - concurrent.preset.learning_rate
    - concurrent.preset.passes
    - concurrent.preset.sample
    - concurrent.preset.seed
    - concurrent.preset.weight_factor
    - concurrent.requests.columns
    - concurrent.requests.estimators
    - concurrent.requests.features
    - concurrent.requests.learning_rate
    - concurrent.requests.max_features
    - concurrent.requests.num_est
    - concurrent.requests.split
    - concurrent.test.dense
    - concurrent.test.estimators
    - concurrent.test.features
    - concurrent.test.folds
    - concurrent.test.min_split
    - concurrent.test.ngrams
    - concurrent.test.num_est
    - concurrent.test.passes
    - concurrent.test.random_state
    - concurrent.test.trees
    - concurrent.test.weight_factor
    - model.combine.drop
    - model.combine.estimators
    - model.combine.features
    - model.combine.layers
    - model.combine.max_depth
    - model.combine.min_features
    - model.combine.sample
    - model.combine.split
    - model.diff.estimators
    - model.diff.features
    - model.diff.learning_rate
    - model.diff.num_est
    - model.diff.seed
    - model.diff.split
    - model.long.columns
    - model.long.learning_rate
    - model.long.max_features
    - model.long.random_state
    - model.long.sample
    - model.long.split
    - model.other.batch_size
    - model.other.learning_rate
    - model.other.max_depth
    - model.other.min_split
    - model.other.ngrams
    - model.other.passes
    - model.other.sample
    - model.other.split
    - model.other.threads
    - model.other.weight_factor
    - model.preset.columns
    - model.preset.folds
    - model.preset.max_depth
    - model.preset.passes
    - model.requests.drop
    - model.requests.estimators
    - model.requests.min_features
    - model.requests.sample
    - model.requests.trees
    - model.test.folds
    - model.test.max_features
    - model.test.min_features
    - model.test.min_split
    - model.test.sample
    - model.test.seed
    - model.test.split
    - model.test.threads
    - preprocessing.combine.features
    - preprocessing.combine.folds
    - preprocessing.combine.learning_rate
    - preprocessing.combine.max_depth
    - preprocessing.combine.max_features
    - preprocessing.combine.min_features
    - preprocessing.combine.min_split
    - preprocessing.combine.sample
    - preprocessing.combine.split
    - preprocessing.combine.weight_factor
    - preprocessing.diff.max_features
    - preprocessing.diff.min_split
    - preprocessing.diff.random_state
    - preprocessing.diff.sample
    - preprocessing.diff.weight_factor
    - preprocessing.long.drop
    - preprocessing.long.features
    - preprocessing.long.passes
    - preprocessing.long.tags
    - preprocessing.other.columns
    - preprocessing.other.epochs
    - preprocessing.other.estimators
    - preprocessing.other.features
    - preprocessing.other.min_split
    - preprocessing.other.tags
    - preprocessing.other.weight_factor
    - preprocessing.preset.features
    - preprocessing.preset.folds
    - preprocessing.preset.max_features
    - preprocessing.preset.sample
    - preprocessing.preset.seed
    - preprocessing.preset.threads
    - preprocessing.requests.folds
    - preprocessing.requests.min_split
    - preprocessing.requests.num_est
    - preprocessing.requests.sample
    - preprocessing.requests.weight_factor
    - preprocessing.test.drop
    - preprocessing.test.features
    - preprocessing.test.layers
    - preprocessing.test.passes
    - preprocessing.test.seed
    - preprocessing.test.tags
    - settings.combine.batch_size
    - settings.combine.epochs
    - settings.combine.estimators
    - settings.combine.learning_rate
    - settings.combine.max_features
    - settings.combine.min_split
    - settings.diff.columns
    - settings.diff.max_depth
    - settings.diff.random_state
    - settings.diff.weight_factor
    - settings.long.folds
    - settings.long.sample
    - settings.other.learning_rate
    - settings.other.max_features
    - settings.other.min_split
    - settings.other.seed
    - settings.other.trees
    - settings.preset.dense
    - settings.preset.drop
    - settings.preset.epochs
    - settings.preset.features
    - settings.preset.folds
    - settings.preset.min_features
    - settings.preset.num_est
    - settings.preset.random_state
    - settings.preset.tags
    - settings.preset.weight_factor
    - settings.requests.batch_size
    - settings.requests.estimators
    - settings.requests.layers
    - settings.requests.max_features
    - settings.requests.min_split
    - settings.requests.num_est
    - settings.requests.random_state
    - settings.requests.threads
    - settings.test.drop
    - settings.test.layers
    - settings.test.learning_rate
    - settings.test.max_features
    - settings.test.random_state
    - tagging.combine.batch_size
    - tagging.combine.estimators
    - tagging.combine.folds
    - tagging.combine.min_split
    - tagging.combine.passes
    - tagging.diff.epochs
    - tagging.diff.layers
    - tagging.diff.max_features
    - tagging.diff.ngrams
    - tagging.diff.random_state
    - tagging.diff.threads
    - tagging.long.columns
    - tagging.long.drop
    - tagging.long.estimators
    - tagging.long.max_depth
    - tagging.long.seed
    - tagging.other.batch_size
    - tagging.other.features
    - tagging.other.layers
    - tagging.other.max_features
    - tagging.other.seed
    - tagging.preset.min_features
    - tagging.preset.min_split
    - tagging.preset.split
    - tagging.requests.columns
    - tagging.requests.epochs
    - tagging.requests.max_depth
    - tagging.requests.max_features
    - tagging.requests.num_est
    - tagging.requests.trees
    - tagging.test.drop
    - tagging.test.epochs
    - tagging.test.estimators
    - tagging.test.folds
    - tagging.test.max_depth
    - tagging.test.sample
    - tagging.test.seed
    - variables.combine.dense
    - variables.combine.features
    - variables.combine.min_features
    - variables.combine.sample
    - variables.diff.max_depth
    - variables.diff.max_features
    - variables.diff.min_split
    - variables.diff.split
    - variables.diff.tags
    - variables.long.estimators
    - variables.long.max_features
    - variables.long.tags
    - variables.long.weight_factor
    - variables.other.columns
    - variables.other.drop
    - variables.other.learning_rate
    - variables.other.passes
    - variables.other.random_state
    - variables.other.split
    - variables.preset.epochs
    - variables.preset.ngrams
    - variables.preset.seed
    - variables.preset.trees
    - variables.preset.weight_factor
    - variables.requests.num_est
    - variables.requests.random_state
    - variables.test.dense
    - variables.test.layers
    - variables.test.passes
    - variables.test.sample
    - variables.test.threads
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json texts-test.csv
    deps:
    - evaluate.py
    - model.json
    - texts-test.csv
    metrics:
    - metrics.json:
        cache: false
