settings:
  preset:
    epochs: 35
    min_features: 1100
    folds: 6
    num_est: 119
    drop: 0.2
    features: 1740
    random_state: 352000000
    tags: 84
    dense: 263
    weight_factor: 0.1
  requests:
    batch_size: 720
    min_split: 39
    layers: 4
    threads: 1
    num_est: 150
    random_state: 41000000
    max_features: 3800
    estimators: 38
  test:
    random_state: 510000000
    learning_rate: 0.04
    layers: 2
    drop: 0.20203
    max_features: 200
  combine:
    max_features: 4450
    min_split: 48
    estimators: 161
    batch_size: 416
    learning_rate: 0.09548
    epochs: 10
  other:
    learning_rate: 0.01
    seed: 430734343
    min_split: 64
    trees: 60
    max_features: 1200
  diff:
    max_depth: 28
    random_state: 137000000
    columns: 39
    weight_factor: 0.2
  long:
    sample: 0.5
    folds: 2
concurrent:
  long:
    num_est: 75
    batch_size: 552
    sample: 1.0
    random_state: 54000000
    split: 0.0934
    min_split: 80
    dense: 500
    ngrams: 4
    folds: 3
    max_depth: 24
  test:
    ngrams: 8
    weight_factor: 0.24244
    estimators: 197
    dense: 500
    random_state: 828000000
    passes: 108
    min_split: 80
    features: 4620
    trees: 51
    folds: 3
    num_est: 100
  requests:
    learning_rate: 0.15
    max_features: 1450
    features: 1590
    num_est: 243
    columns: 15
    split: 0.5
    estimators: 95
  diff:
    trees: 36
    tags: 119
    max_depth: 8
    columns: 48
    seed: 483630000
    sample: 0.5
  preset:
    sample: 0.75
    features: 1730
    weight_factor: 0.3
    seed: 608662429
    learning_rate: 0.04
    passes: 94
    layers: 6
  other:
    tags: 70
    max_depth: 32
  combine:
    epochs: 50
model:
  combine:
    min_features: 100
    max_depth: 4
    sample: 0.71713
    estimators: 180
    features: 411
    split: 0.09422
    layers: 2
    drop: 0.4
  preset:
    columns: 21
    folds: 9
    passes: 92
    max_depth: 24
  diff:
    split: 0.4
    seed: 319448000
    num_est: 50
    learning_rate: 0.1
    estimators: 154
    features: 4310
  long:
    learning_rate: 0.13186
    sample: 0.75
    columns: 57
    split: 0.5
    max_features: 2350
    random_state: 402365341
  other:
    sample: 0.87009
    max_depth: 20
    weight_factor: 0.2
    min_split: 54
    batch_size: 976
    threads: 1
    split: 0.3
    ngrams: 6
    passes: 104
    learning_rate: 0.07
  test:
    min_split: 80
    min_features: 3675
    threads: 1
    max_features: 1568
    folds: 3
    seed: 761722981
    split: 0.4
    sample: 0.25
  requests:
    estimators: 112
    min_features: 1400
    trees: 12
    sample: 0.5
    drop: 0.23695
prepare:
  test:
    num_est: 243
    sample: 1.0
    trees: 12
    features: 1470
    columns: 81
  preset:
    max_depth: 8
    seed: 230183000
    folds: 9
    estimators: 131
    dense: 361
    learning_rate: 0.04325
    min_features: 4400
  requests:
    passes: 59
    epochs: 15
    weight_factor: 0.2
    random_state: 399465806
  long:
    trees: 81
    features: 4820
    dense: 100
    sample: 0.5247
    max_depth: 32
    epochs: 53
    weight_factor: 0.3
  combine:
    dense: 187
    weight_factor: 0.1
    folds: 4
    features: 12
    split: 0.23216
    learning_rate: 0.03341
  other:
    random_state: 20776859
    trees: 55
    split: 0.1
  diff:
    epochs: 20
    estimators: 134
variables:
  preset:
    weight_factor: 0.3
    epochs: 75
    seed: 338444000
    trees: 12
    ngrams: 2
  long:
    estimators: 80
    tags: 28
    weight_factor: 0.23348
    max_features: 1500
  test:
    threads: 7
    layers: 4
    passes: 102
    sample: 0.5
    dense: 500
  diff:
    split: 0.5
    min_split: 17
    max_features: 50
    tags: 56
    max_depth: 33
  requests:
    num_est: 125
    random_state: 310000000
  combine:
    sample: 0.75
    features: 4320
    dense: 200
    min_features: 1300
  other:
    passes: 40
    columns: 54
    learning_rate: 0.02
    split: 0.4
    random_state: 975000000
    drop: 0.4
preprocessing:
  requests:
    num_est: 250
    weight_factor: 0.19355
    folds: 9
    min_split: 64
    sample: 0.25
  preset:
    features: 4590
    sample: 0.25
    max_features: 2750
    seed: 430623000
    folds: 5
    threads: 31
  combine:
    sample: 0.25
    learning_rate: 0.08
    weight_factor: 0.3
    max_features: 500
    features: 4000
    min_features: 250
    folds: 9
    split: 0.1
    max_depth: 20
    min_split: 35
  other:
    min_split: 48
    epochs: 70
    features: 3540
    weight_factor: 0.2
    tags: 63
    columns: 19
    estimators: 184
  diff:
    weight_factor: 0.2
    sample: 0.75
    min_split: 48
    max_features: 150
    random_state: 307000000
  test:
    layers: 6
    drop: 0.1
    seed: 523834000
    features: 2006
    passes: 86
    tags: 42
  long:
    drop: 0.2
    passes: 16
    tags: 105
    features: 1270
tagging:
  other:
    batch_size: 960
    features: 4710
    layers: 6
    seed: 945811000
    max_features: 4000
  requests:
    max_depth: 33
    num_est: 225
    max_features: 1201
    epochs: 70
    columns: 27
    trees: 48
  diff:
    epochs: 40
    layers: 4
    ngrams: 4
    threads: 2
    max_features: 250
    random_state: 444362324
  long:
    columns: 30
    estimators: 210
    max_depth: 16
    seed: 88221000
    drop: 0.32367
  preset:
    split: 0.4
    min_features: 3350
    min_split: 43
  test:
    folds: 9
    epochs: 20
    max_depth: 20
    sample: 0.5
    drop: 0.49594
    estimators: 243
    seed: 209733000
  combine:
    min_split: 16
    estimators: 147
    batch_size: 80
    passes: 114
    folds: 3
