model:
  rf:
    max_depth: 22
    min_features: 1008
    weight_factor: 0.11089
    batch_size: 1061
    trees: 42
  batch:
    layers: 5
    min_split: 58
    split: 0.1648
    max_depth: 13
  short:
    min_split: 14
    trees: 54
    epochs: 39
    learning_rate: 0.07731
  preset:
    ngrams: 4
    split: 0.45522
    folds: 7
    epochs: 21
  binary:
    ngrams: 7
    epochs: 16
    sample: 0.24183
    min_features: 242
    dense: 592
    tags: 8
  long:
    min_features: 2950
    learning_rate: 0.13491
    split: 0.22043
  dev:
    folds: 8
tagging:
  rf:
    max_depth: 9
    epochs: 10
    threads: 16
    random_state: 368429446
  dev:
    threads: 24
    features: 530
    sample: 0.75694
    columns: 19
    dense: 285
    min_split: 61
  binary:
    weight_factor: 0.09189
    ngrams: 5
    min_split: 45
  preset:
    seed: 129803821
    batch_size: 94
    estimators: 82
  long:
    features: 3147
    layers: 2
    min_features: 3064
  short:
    dense: 219
    threads: 3
  batch:
    sample: 0.58803
    dense: 213
    num_est: 195
train:
  dev:
    sample: 0.5
    batch_size: 373
    learning_rate: 0.10853
  rf:
    passes: 14
    num_est: 186
  binary:
    learning_rate: 0.16241
    max_features: 120
  batch:
    drop: 0.23801
    tags: 90
  preset:
    num_est: 308
    features: 420
    drop: 0.49652
  short:
    min_split: 79
featurize:
  binary:
    features: 2927
    passes: 7
    drop: 0.21663
    estimators: 226
    ngrams: 7
    tags: 81
  long:
    ngrams: 7
    tags: 89
    folds: 10
    seed: 243856187
    sample: 0.58417
    epochs: 74
    max_features: 2312
  preset:
    estimators: 272
    max_features: 2283
    passes: 85
  dev:
    min_split: 62
    trees: 33
    sample: 0.26591
    seed: 551590437
    min_features: 3377
    batch_size: 48
  rf:
    folds: 7
  short:
    trees: 63
    threads: 12
  batch:
    ngrams: 8
preprocessing:
  preset:
    split: 0.55897
    dense: 101
    tags: 128
    epochs: 83
  binary:
    dense: 326
    ngrams: 6
    split: 0.50256
    weight_factor: 0.09433
    max_depth: 26
  rf:
    threads: 7
    weight_factor: 0.1
  dev:
    weight_factor: 0.37446
    learning_rate: 0.0332
  long:
    layers: 4
    weight_factor: 0.23524
    learning_rate: 0.01158
    ngrams: 3
  short:
    max_features: 1995
    epochs: 54
  batch:
    estimators: 87
    ngrams: 2
    min_split: 29
settings:
  preset:
    epochs: 48
    tags: 24
    columns: 78
    drop: 0.07732
    ngrams: 2
  long:
    min_features: 677
    features: 1140
    min_split: 82
  short:
    estimators: 41
    max_depth: 20
  dev:
    sample: 0.56569
    min_split: 50
  rf:
    learning_rate: 0.04168
    num_est: 119
    min_features: 1407
    seed: 688056171
  batch:
    learning_rate: 0.08786
    columns: 6
    trees: 63
    batch_size: 776
  binary:
    min_split: 60
    batch_size: 31
    max_features: 1730
    features: 3593
    passes: 4
    split: 0.29189
    ngrams: 2
validation:
  long:
    ngrams: 6
    random_state: 1008142457
    passes: 30
    batch_size: 188
    weight_factor: 0.29629
  batch:
    sample: 0.61316
    layers: 4
  binary:
    max_depth: 8
    num_est: 272
    learning_rate: 0.12033
    split: 0.19402
    weight_factor: 0.3
  short:
    layers: 1
    min_split: 80
    columns: 33
    folds: 2
  rf:
    threads: 7
    passes: 116
    max_features: 3055
    max_depth: 31
  dev:
    trees: 3
    dense: 340
    features: 5573
    threads: 9
    min_features: 1788
    num_est: 181
    learning_rate: 0.1485
  preset:
    learning_rate: 0.12913
    ngrams: 8
    weight_factor: 0.2755
