model:
  rf:
    max_depth: 24
    min_features: 1050
    weight_factor: 0.1
    batch_size: 1061
    trees: 39
  batch:
    layers: 7
    min_split: 48
    split: 0.2
    max_depth: 19
  short:
    min_split: 16
    trees: 54
    epochs: 45
    learning_rate: 0.07
  preset:
    ngrams: 4
    split: 0.49705
    folds: 9
    epochs: 20
  binary:
    ngrams: 6
    epochs: 15
    sample: 0.23537
    min_features: 200
    dense: 448
    tags: 6
  long:
    min_features: 2950
    learning_rate: 0.10401
    split: 0.2
  dev:
    folds: 9
tagging:
  rf:
    max_depth: 8
    epochs: 10
    threads: 16
    random_state: 420000000
  dev:
    threads: 31
    features: 530
    sample: 0.77583
    columns: 18
    dense: 311
    min_split: 80
  binary:
    weight_factor: 0.09189
    ngrams: 4
    min_split: 48
  preset:
    seed: 156117000
    batch_size: 98
    estimators: 82
  long:
    features: 3463
    layers: 2
    min_features: 3711
  short:
    dense: 235
    threads: 3
  batch:
    sample: 0.75
    dense: 200
    num_est: 200
train:
  dev:
    sample: 0.5
    batch_size: 317
    learning_rate: 0.13
  rf:
    passes: 14
    num_est: 150
  binary:
    learning_rate: 0.13
    max_features: 164
  batch:
    drop: 0.23801
    tags: 102
  preset:
    num_est: 308
    features: 420
    drop: 0.323
  short:
    min_split: 69
featurize:
  binary:
    features: 2880
    passes: 9
    drop: 0.2
    estimators: 225
    ngrams: 6
    tags: 70
  long:
    ngrams: 8
    tags: 98
    folds: 12
    seed: 324388000
    sample: 0.5
    epochs: 73
    max_features: 2800
  preset:
    estimators: 235
    max_features: 2550
    passes: 74
  dev:
    min_split: 80
    trees: 36
    sample: 0.25
    seed: 666054000
    min_features: 3550
    batch_size: 36
  rf:
    folds: 9
  short:
    trees: 69
    threads: 14
  batch:
    ngrams: 8
preprocessing:
  preset:
    split: 0.5
    dense: 100
    tags: 112
    epochs: 75
  binary:
    dense: 300
    ngrams: 6
    split: 0.54841
    weight_factor: 0.1
    max_depth: 26
  rf:
    threads: 7
    weight_factor: 0.1
  dev:
    weight_factor: 0.23385
    learning_rate: 0.04
  long:
    layers: 4
    weight_factor: 0.2
    learning_rate: 0.01
    ngrams: 3
  short:
    max_features: 2600
    epochs: 45
  batch:
    estimators: 106
    ngrams: 2
    min_split: 32
settings:
  preset:
    epochs: 60
    tags: 23
    columns: 78
    drop: 0.1
    ngrams: 2
  long:
    min_features: 906
    features: 1140
    min_split: 80
  short:
    estimators: 53
    max_depth: 17
  dev:
    sample: 0.5
    min_split: 48
  rf:
    learning_rate: 0.06232
    num_est: 89
    min_features: 1450
    seed: 855941000
  batch:
    learning_rate: 0.07997
    columns: 5
    trees: 76
    batch_size: 864
  binary:
    min_split: 80
    batch_size: 31
    max_features: 2250
    features: 3593
    passes: 6
    split: 0.36811
    ngrams: 2
validation:
  long:
    ngrams: 8
    random_state: 972000000
    passes: 26
    batch_size: 224
    weight_factor: 0.32189
  batch:
    sample: 0.75
    layers: 4
  binary:
    max_depth: 8
    num_est: 244
    learning_rate: 0.1
    split: 0.2
    weight_factor: 0.3
  short:
    layers: 2
    min_split: 80
    columns: 33
    folds: 3
  rf:
    threads: 7
    passes: 114
    max_features: 2650
    max_depth: 33
  dev:
    trees: 3
    dense: 300
    features: 4890
    threads: 11
    min_features: 1900
    num_est: 200
    learning_rate: 0.13686
  preset:
    learning_rate: 0.12187
    ngrams: 8
    weight_factor: 0.2755
