model:
  rf:
    max_depth: 20
    min_features: 1008
    weight_factor: 0.11089
    batch_size: 1061
    trees: 42
  batch:
    layers: 7
    min_split: 48
    split: 0.2
    max_depth: 13
  short:
    min_split: 14
    trees: 54
    epochs: 39
    learning_rate: 0.07731
  preset:
    ngrams: 4
    split: 0.45522
    folds: 9
    epochs: 21
  binary:
    ngrams: 7
    epochs: 15
    sample: 0.24183
    min_features: 242
    dense: 592
    tags: 8
  long:
    min_features: 2950
    learning_rate: 0.13491
    split: 0.22043
  dev:
    folds: 6
tagging:
  rf:
    max_depth: 8
    epochs: 10
    threads: 16
    random_state: 368429446
  dev:
    threads: 28
    features: 530
    sample: 0.75694
    columns: 14
    dense: 285
    min_split: 97
  binary:
    weight_factor: 0.09189
    ngrams: 5
    min_split: 48
  preset:
    seed: 129803821
    batch_size: 94
    estimators: 82
  long:
    features: 3463
    layers: 2
    min_features: 2964
  short:
    dense: 160
    threads: 3
  batch:
    sample: 0.58803
    dense: 213
    num_est: 195
train:
  dev:
    sample: 0.5
    batch_size: 317
    learning_rate: 0.13
  rf:
    passes: 14
    num_est: 186
  binary:
    learning_rate: 0.12467
    max_features: 120
  batch:
    drop: 0.23801
    tags: 90
  preset:
    num_est: 308
    features: 420
    drop: 0.323
  short:
    min_split: 54
featurize:
  binary:
    features: 2927
    passes: 9
    drop: 0.21663
    estimators: 250
    ngrams: 4
    tags: 56
  long:
    ngrams: 8
    tags: 72
    folds: 11
    seed: 358696406
    sample: 0.41402
    epochs: 56
    max_features: 2754
  preset:
    estimators: 187
    max_features: 2843
    passes: 60
  dev:
    min_split: 93
    trees: 31
    sample: 0.25133
    seed: 720026092
    min_features: 3281
    batch_size: 48
  rf:
    folds: 7
  short:
    trees: 76
    threads: 10
  batch:
    ngrams: 7
preprocessing:
  preset:
    split: 0.55897
    dense: 95
    tags: 115
    epochs: 83
  binary:
    dense: 326
    ngrams: 6
    split: 0.50256
    weight_factor: 0.12261
    max_depth: 26
  rf:
    threads: 7
    weight_factor: 0.1
  dev:
    weight_factor: 0.37446
    learning_rate: 0.0332
  long:
    layers: 4
    weight_factor: 0.23524
    learning_rate: 0.01
    ngrams: 3
  short:
    max_features: 2359
    epochs: 54
  batch:
    estimators: 87
    ngrams: 2
    min_split: 29
settings:
  preset:
    epochs: 60
    tags: 23
    columns: 78
    drop: 0.07732
    ngrams: 2
  long:
    min_features: 906
    features: 1140
    min_split: 67
  short:
    estimators: 46
    max_depth: 16
  dev:
    sample: 0.50453
    min_split: 47
  rf:
    learning_rate: 0.05772
    num_est: 91
    min_features: 1582
    seed: 688056171
  batch:
    learning_rate: 0.08786
    columns: 6
    trees: 63
    batch_size: 776
  binary:
    min_split: 60
    batch_size: 31
    max_features: 2372
    features: 3593
    passes: 4
    split: 0.29622
    ngrams: 2
validation:
  long:
    ngrams: 8
    random_state: 1197221276
    passes: 30
    batch_size: 194
    weight_factor: 0.36804
  batch:
    sample: 0.78031
    layers: 4
  binary:
    max_depth: 6
    num_est: 272
    learning_rate: 0.1
    split: 0.19402
    weight_factor: 0.3
  short:
    layers: 1
    min_split: 80
    columns: 33
    folds: 2
  rf:
    threads: 7
    passes: 97
    max_features: 3055
    max_depth: 31
  dev:
    trees: 3
    dense: 340
    features: 5573
    threads: 9
    min_features: 2113
    num_est: 200
    learning_rate: 0.1485
  preset:
    learning_rate: 0.12187
    ngrams: 8
    weight_factor: 0.2755
