model:
  rf:
    max_depth: 26
    min_features: 1042
    weight_factor: 0.07687
    batch_size: 1061
    trees: 39
  batch:
    layers: 7
    min_split: 48
    split: 0.2
    max_depth: 13
  short:
    min_split: 16
    trees: 54
    epochs: 45
    learning_rate: 0.07553
  preset:
    ngrams: 4
    split: 0.45522
    folds: 6
    epochs: 20
  binary:
    ngrams: 7
    epochs: 15
    sample: 0.22102
    min_features: 214
    dense: 548
    tags: 8
  long:
    min_features: 2950
    learning_rate: 0.13491
    split: 0.22043
  dev:
    folds: 9
tagging:
  rf:
    max_depth: 8
    epochs: 10
    threads: 14
    random_state: 426265819
  dev:
    threads: 31
    features: 530
    sample: 0.75694
    columns: 14
    dense: 285
    min_split: 97
  binary:
    weight_factor: 0.09189
    ngrams: 6
    min_split: 48
  preset:
    seed: 129803821
    batch_size: 98
    estimators: 82
  long:
    features: 3463
    layers: 1
    min_features: 2964
  short:
    dense: 203
    threads: 3
  batch:
    sample: 0.75
    dense: 187
    num_est: 200
train:
  dev:
    sample: 0.5
    batch_size: 317
    learning_rate: 0.13
  rf:
    passes: 14
    num_est: 114
  binary:
    learning_rate: 0.12467
    max_features: 120
  batch:
    drop: 0.23801
    tags: 102
  preset:
    num_est: 308
    features: 420
    drop: 0.323
  short:
    min_split: 54
featurize:
  binary:
    features: 2927
    passes: 6
    drop: 0.15749
    estimators: 241
    ngrams: 5
    tags: 75
  long:
    ngrams: 9
    tags: 90
    folds: 12
    seed: 309961536
    sample: 0.39696
    epochs: 87
    max_features: 3092
  preset:
    estimators: 180
    max_features: 2532
    passes: 73
  dev:
    min_split: 64
    trees: 33
    sample: 0.25
    seed: 620192343
    min_features: 3598
    batch_size: 37
  rf:
    folds: 7
  short:
    trees: 62
    threads: 10
  batch:
    ngrams: 8
preprocessing:
  preset:
    split: 0.55897
    dense: 95
    tags: 115
    epochs: 83
  binary:
    dense: 262
    ngrams: 5
    split: 0.50256
    weight_factor: 0.07695
    max_depth: 26
  rf:
    threads: 7
    weight_factor: 0.1
  dev:
    weight_factor: 0.37446
    learning_rate: 0.04
  long:
    layers: 4
    weight_factor: 0.23524
    learning_rate: 0.01
    ngrams: 3
  short:
    max_features: 2614
    epochs: 54
  batch:
    estimators: 87
    ngrams: 2
    min_split: 29
settings:
  preset:
    epochs: 60
    tags: 23
    columns: 78
    drop: 0.07732
    ngrams: 2
  long:
    min_features: 906
    features: 1140
    min_split: 80
  short:
    estimators: 61
    max_depth: 16
  dev:
    sample: 0.50453
    min_split: 43
  rf:
    learning_rate: 0.04827
    num_est: 89
    min_features: 1225
    seed: 688056171
  batch:
    learning_rate: 0.08786
    columns: 6
    trees: 63
    batch_size: 996
  binary:
    min_split: 80
    batch_size: 31
    max_features: 2372
    features: 3593
    passes: 7
    split: 0.36811
    ngrams: 2
validation:
  long:
    ngrams: 8
    random_state: 972000000
    passes: 21
    batch_size: 194
    weight_factor: 0.36804
  batch:
    sample: 0.78031
    layers: 4
  binary:
    max_depth: 6
    num_est: 272
    learning_rate: 0.1
    split: 0.19402
    weight_factor: 0.3
  short:
    layers: 2
    min_split: 80
    columns: 33
    folds: 3
  rf:
    threads: 7
    passes: 97
    max_features: 2135
    max_depth: 21
  dev:
    trees: 3
    dense: 300
    features: 5573
    threads: 11
    min_features: 2113
    num_est: 198
    learning_rate: 0.13686
  preset:
    learning_rate: 0.12187
    ngrams: 8
    weight_factor: 0.2755
