settings:
  max_depth: 4
  epochs: 55
  tags: 7
  min_features: 1450
  threads: 19
  estimators: 182
  num_est: 50
  ngrams: 4
  max_features: 368
  seed: 694646561
  batch_size: 656
  dense: 400
  passes: 16
  columns: 21
  random_state: 869548485
  trees: 62
  min_split: 30
  split: 0.30196
  drop: 0.17815
  layers: 4
concurrent:
  weight_factor: 0.10509
  sample: 0.27269
  ngrams: 4
  min_split: 16
  num_est: 25
  drop: 0.3
  random_state: 255764941
  threads: 3
  passes: 93
  tags: 98
  features: 2344
  folds: 6
  dense: 215
  trees: 64
  columns: 42
  epochs: 45
  learning_rate: 0.04
  max_features: 4435
  min_features: 800
  seed: 825243000
  batch_size: 144
  estimators: 180
variables:
  min_features: 2000
  learning_rate: 0.09
  columns: 20
  estimators: 36
  max_depth: 9
  seed: 698881232
  passes: 77
  random_state: 988485972
  sample: 0.30464
  tags: 112
  min_split: 80
  num_est: 199
  folds: 3
  dense: 287
  split: 0.375
  batch_size: 758
  features: 3900
  max_features: 3448
  ngrams: 2
  layers: 2
  drop: 0.33054
prepare:
  weight_factor: 0.09514
  passes: 19
  drop: 0.1048
  sample: 0.56112
  estimators: 213
  tags: 100
  trees: 76
  learning_rate: 0.10888
  layers: 1
  num_est: 52
  random_state: 534316482
  columns: 62
  epochs: 18
  dense: 232
  ngrams: 5
  batch_size: 584
  min_split: 19
  min_features: 2865
  features: 4366
  max_depth: 10
  folds: 7
tagging:
  drop: 0.39455
  ngrams: 3
  threads: 16
  num_est: 57
  batch_size: 931
  layers: 2
  estimators: 35
  folds: 6
  weight_factor: 0.09603
  columns: 58
  trees: 91
  learning_rate: 0.13
  seed: 952765000
  dense: 500
  max_depth: 9
  min_features: 2150
  sample: 0.25
  tags: 106
  epochs: 56
  features: 2363
