settings:
  max_depth: 4
  epochs: 55
  tags: 6
  min_features: 1450
  threads: 19
  estimators: 200
  num_est: 59
  ngrams: 4
  max_features: 257
  seed: 694646561
  batch_size: 510
  dense: 313
  passes: 16
  columns: 16
  random_state: 869548485
  trees: 45
  min_split: 31
  split: 0.30196
  drop: 0.20075
  layers: 3
concurrent:
  weight_factor: 0.10509
  sample: 0.27269
  ngrams: 4
  min_split: 16
  num_est: 25
  drop: 0.3
  random_state: 280136626
  threads: 2
  passes: 93
  tags: 82
  features: 2344
  folds: 4
  dense: 215
  trees: 52
  columns: 42
  epochs: 45
  learning_rate: 0.03524
  max_features: 5073
  min_features: 800
  seed: 966366795
  batch_size: 126
  estimators: 180
variables:
  min_features: 1537
  learning_rate: 0.09
  columns: 20
  estimators: 36
  max_depth: 9
  seed: 698881232
  passes: 55
  random_state: 988485972
  sample: 0.30464
  tags: 90
  min_split: 66
  num_est: 191
  folds: 3
  dense: 287
  split: 0.375
  batch_size: 552
  features: 4189
  max_features: 2913
  ngrams: 2
  layers: 2
  drop: 0.33054
prepare:
  weight_factor: 0.10186
  passes: 27
  drop: 0.11137
  sample: 0.57242
  estimators: 237
  tags: 124
  trees: 80
  learning_rate: 0.14299
  layers: 1
  num_est: 41
  random_state: 835215566
  columns: 54
  epochs: 12
  dense: 228
  ngrams: 4
  batch_size: 443
  min_split: 15
  min_features: 2750
  features: 3824
  max_depth: 10
  folds: 7
tagging:
  drop: 0.30093
  ngrams: 3
  threads: 15
  num_est: 43
  batch_size: 837
  layers: 1
  estimators: 35
  folds: 6
  weight_factor: 0.09603
  columns: 58
  trees: 97
  learning_rate: 0.15693
  seed: 952765000
  dense: 434
  max_depth: 12
  min_features: 1793
  sample: 0.25
  tags: 80
  epochs: 56
  features: 2363
