settings:
  max_depth: 4
  epochs: 55
  tags: 7
  min_features: 1450
  threads: 18
  estimators: 171
  num_est: 50
  ngrams: 4
  max_features: 300
  seed: 893727687
  batch_size: 656
  dense: 400
  passes: 16
  columns: 21
  random_state: 869548485
  trees: 57
  min_split: 30
  split: 0.3
  drop: 0.17815
  layers: 4
concurrent:
  weight_factor: 0.10509
  sample: 0.27269
  ngrams: 7
  min_split: 16
  num_est: 25
  drop: 0.3
  random_state: 256000000
  threads: 3
  passes: 98
  tags: 98
  features: 2810
  folds: 6
  dense: 200
  trees: 69
  columns: 42
  epochs: 45
  learning_rate: 0.04
  max_features: 4435
  min_features: 800
  seed: 825243000
  batch_size: 144
  estimators: 154
variables:
  min_features: 2000
  learning_rate: 0.09
  columns: 27
  estimators: 47
  max_depth: 12
  seed: 901562702
  passes: 66
  random_state: 937000000
  sample: 0.22269
  tags: 112
  min_split: 80
  num_est: 199
  folds: 2
  dense: 300
  split: 0.30223
  batch_size: 608
  features: 3900
  max_features: 3016
  ngrams: 2
  layers: 2
  drop: 0.3
prepare:
  weight_factor: 0.09172
  passes: 21
  drop: 0.1199
  sample: 0.56112
  estimators: 187
  tags: 129
  trees: 85
  learning_rate: 0.12335
  layers: 1
  num_est: 52
  random_state: 687403489
  columns: 61
  epochs: 18
  dense: 195
  ngrams: 6
  batch_size: 647
  min_split: 14
  min_features: 2845
  features: 4079
  max_depth: 12
  folds: 6
tagging:
  drop: 0.47753
  ngrams: 4
  threads: 16
  num_est: 44
  batch_size: 912
  layers: 2
  estimators: 44
  folds: 6
  weight_factor: 0.1
  columns: 58
  trees: 78
  learning_rate: 0.13
  seed: 952765000
  dense: 500
  max_depth: 12
  min_features: 2150
  sample: 0.25
  tags: 111
  epochs: 50
  features: 1906
