settings:
  max_depth: 4
  epochs: 55
  tags: 7
  min_features: 1450
  threads: 18
  estimators: 171
  num_est: 50
  ngrams: 4
  max_features: 300
  seed: 789390000
  batch_size: 656
  dense: 400
  passes: 16
  columns: 21
  random_state: 1008347812
  trees: 60
  min_split: 32
  split: 0.3
  drop: 0.17815
  layers: 4
concurrent:
  weight_factor: 0.1
  sample: 0.25
  ngrams: 6
  min_split: 16
  num_est: 25
  drop: 0.3
  random_state: 256000000
  threads: 2
  passes: 98
  tags: 98
  features: 2810
  folds: 6
  dense: 200
  trees: 69
  columns: 42
  epochs: 45
  learning_rate: 0.04
  max_features: 4435
  min_features: 800
  seed: 825243000
  batch_size: 144
  estimators: 154
variables:
  min_features: 2000
  learning_rate: 0.09
  columns: 27
  estimators: 47
  max_depth: 12
  seed: 814518000
  passes: 66
  random_state: 937000000
  sample: 0.25
  tags: 112
  min_split: 80
  num_est: 200
  folds: 3
  dense: 300
  split: 0.4
  batch_size: 608
  features: 3900
  max_features: 3800
  ngrams: 2
  layers: 2
  drop: 0.3
prepare:
  weight_factor: 0.12289
  passes: 27
  drop: 0.08111
  sample: 0.50039
  estimators: 213
  tags: 124
  trees: 89
  learning_rate: 0.14509
  layers: 2
  num_est: 42
  random_state: 665637473
  columns: 61
  epochs: 15
  dense: 233
  ngrams: 5
  batch_size: 570
  min_split: 12
  min_features: 1909
  features: 4414
  max_depth: 12
  folds: 7
tagging:
  drop: 0.4
  ngrams: 4
  threads: 14
  num_est: 50
  batch_size: 912
  layers: 2
  estimators: 44
  folds: 6
  weight_factor: 0.1
  columns: 54
  trees: 78
  learning_rate: 0.13
  seed: 952765000
  dense: 500
  max_depth: 12
  min_features: 2150
  sample: 0.25
  tags: 105
  epochs: 50
  features: 2460
