settings:
  max_depth: 4
  epochs: 55
  tags: 7
  min_features: 1450
  threads: 19
  estimators: 200
  num_est: 50
  ngrams: 4
  max_features: 257
  seed: 694646561
  batch_size: 656
  dense: 425
  passes: 16
  columns: 21
  random_state: 869548485
  trees: 45
  min_split: 30
  split: 0.30196
  drop: 0.17815
  layers: 3
concurrent:
  weight_factor: 0.10509
  sample: 0.27269
  ngrams: 4
  min_split: 16
  num_est: 25
  drop: 0.3
  random_state: 280136626
  threads: 3
  passes: 93
  tags: 98
  features: 2344
  folds: 6
  dense: 215
  trees: 64
  columns: 42
  epochs: 45
  learning_rate: 0.04
  max_features: 4149
  min_features: 800
  seed: 825243000
  batch_size: 132
  estimators: 180
variables:
  min_features: 1537
  learning_rate: 0.09
  columns: 20
  estimators: 36
  max_depth: 9
  seed: 698881232
  passes: 77
  random_state: 988485972
  sample: 0.30464
  tags: 112
  min_split: 80
  num_est: 191
  folds: 3
  dense: 287
  split: 0.375
  batch_size: 552
  features: 3900
  max_features: 3448
  ngrams: 2
  layers: 2
  drop: 0.33054
prepare:
  weight_factor: 0.08766
  passes: 28
  drop: 0.11029
  sample: 0.40483
  estimators: 213
  tags: 108
  trees: 61
  learning_rate: 0.09624
  layers: 2
  num_est: 49
  random_state: 534316482
  columns: 54
  epochs: 12
  dense: 245
  ngrams: 7
  batch_size: 509
  min_split: 17
  min_features: 2741
  features: 4808
  max_depth: 14
  folds: 7
tagging:
  drop: 0.30093
  ngrams: 3
  threads: 16
  num_est: 43
  batch_size: 931
  layers: 2
  estimators: 35
  folds: 6
  weight_factor: 0.09603
  columns: 58
  trees: 93
  learning_rate: 0.15693
  seed: 952765000
  dense: 434
  max_depth: 14
  min_features: 2064
  sample: 0.25
  tags: 106
  epochs: 56
  features: 2363
