settings:
  max_depth: 4
  epochs: 55
  tags: 7
  min_features: 1450
  threads: 19
  estimators: 182
  num_est: 50
  ngrams: 4
  max_features: 368
  seed: 694646561
  batch_size: 656
  dense: 400
  passes: 16
  columns: 21
  random_state: 869548485
  trees: 62
  min_split: 30
  split: 0.30196
  drop: 0.17815
  layers: 4
concurrent:
  weight_factor: 0.10509
  sample: 0.27269
  ngrams: 4
  min_split: 16
  num_est: 25
  drop: 0.3
  random_state: 256000000
  threads: 3
  passes: 93
  tags: 98
  features: 2810
  folds: 6
  dense: 245
  trees: 69
  columns: 42
  epochs: 45
  learning_rate: 0.04
  max_features: 4435
  min_features: 800
  seed: 825243000
  batch_size: 144
  estimators: 180
variables:
  min_features: 2000
  learning_rate: 0.09
  columns: 20
  estimators: 36
  max_depth: 9
  seed: 698881232
  passes: 61
  random_state: 940158371
  sample: 0.22269
  tags: 112
  min_split: 80
  num_est: 199
  folds: 2
  dense: 319
  split: 0.375
  batch_size: 758
  features: 3900
  max_features: 3448
  ngrams: 2
  layers: 2
  drop: 0.33054
prepare:
  weight_factor: 0.09514
  passes: 19
  drop: 0.1048
  sample: 0.56112
  estimators: 213
  tags: 100
  trees: 76
  learning_rate: 0.14901
  layers: 1
  num_est: 52
  random_state: 859093353
  columns: 62
  epochs: 18
  dense: 184
  ngrams: 5
  batch_size: 584
  min_split: 19
  min_features: 2865
  features: 5062
  max_depth: 12
  folds: 7
tagging:
  drop: 0.4705
  ngrams: 4
  threads: 16
  num_est: 38
  batch_size: 931
  layers: 2
  estimators: 35
  folds: 6
  weight_factor: 0.1
  columns: 58
  trees: 87
  learning_rate: 0.13
  seed: 952765000
  dense: 500
  max_depth: 9
  min_features: 2150
  sample: 0.25
  tags: 111
  epochs: 50
  features: 2363
