stages:
  split:
    cmd: python split.py users.csv users-train.csv users-test.csv
    deps:
    - split.py
    - users.csv
    outs:
    - users-test.csv
    - users-train.csv
  featurize:
    cmd: python featurize.py users-train.csv users-train-feats.csv
    deps:
    - featurize.py
    - users-train.csv
    outs:
    - users-train-feats.csv
  train:
    cmd: python train.py users-train-feats.csv model.json
    deps:
    - train.py
    - users-train-feats.csv
    params:
    - concurrent.batch.threads
    - concurrent.batch.trees
    - concurrent.dev.estimators
    - concurrent.dev.split
    - concurrent.dev.threads
    - concurrent.dev.trees
    - concurrent.other.drop
    - concurrent.other.estimators
    - concurrent.other.folds
    - concurrent.other.min_features
    - concurrent.other.split
    - concurrent.preset.columns
    - concurrent.preset.dense
    - concurrent.preset.max_depth
    - concurrent.preset.num_est
    - concurrent.preset.split
    - concurrent.preset.tags
    - concurrent.settings.columns
    - concurrent.settings.drop
    - concurrent.settings.features
    - concurrent.settings.max_features
    - concurrent.settings.min_features
    - concurrent.short.epochs
    - concurrent.short.estimators
    - concurrent.short.features
    - concurrent.short.min_split
    - concurrent.short.num_est
    - concurrent.test.batch_size
    - concurrent.test.drop
    - concurrent.test.learning_rate
    - concurrent.test.max_features
    - concurrent.test.min_features
    - concurrent.test.sample
    - concurrent.test.tags
    - concurrent.test.trees
    - model.dev.dense
    - model.dev.estimators
    - model.dev.learning_rate
    - model.dev.max_depth
    - model.dev.seed
    - model.dev.tags
    - model.other.batch_size
    - model.other.columns
    - model.other.ngrams
    - model.preset.drop
    - model.settings.batch_size
    - model.settings.columns
    - model.settings.epochs
    - model.settings.sample
    - model.short.dense
    - model.short.folds
    - model.short.sample
    - model.test.estimators
    - model.test.layers
    - model.test.random_state
    - model.test.weight_factor
    - preprocessing.batch.batch_size
    - preprocessing.batch.features
    - preprocessing.batch.layers
    - preprocessing.batch.learning_rate
    - preprocessing.batch.min_features
    - preprocessing.batch.ngrams
    - preprocessing.batch.split
    - preprocessing.batch.trees
    - preprocessing.dev.batch_size
    - preprocessing.dev.folds
    - preprocessing.dev.trees
    - preprocessing.other.drop
    - preprocessing.other.epochs
    - preprocessing.other.sample
    - preprocessing.other.trees
    - preprocessing.preset.columns
    - preprocessing.preset.learning_rate
    - preprocessing.settings.columns
    - preprocessing.settings.layers
    - preprocessing.settings.min_features
    - preprocessing.settings.num_est
    - preprocessing.settings.sample
    - preprocessing.settings.seed
    - preprocessing.settings.threads
    - preprocessing.settings.weight_factor
    - preprocessing.short.folds
    - preprocessing.short.split
    - preprocessing.test.columns
    - preprocessing.test.dense
    - preprocessing.test.min_features
    - preprocessing.test.ngrams
    - preprocessing.test.tags
    - tagging.batch.batch_size
    - tagging.batch.drop
    - tagging.batch.max_features
    - tagging.batch.min_split
    - tagging.batch.seed
    - tagging.dev.dense
    - tagging.dev.folds
    - tagging.dev.ngrams
    - tagging.dev.num_est
    - tagging.dev.seed
    - tagging.dev.tags
    - tagging.other.ngrams
    - tagging.preset.ngrams
    - tagging.preset.num_est
    - tagging.preset.seed
    - tagging.settings.epochs
    - tagging.settings.learning_rate
    - tagging.settings.trees
    - tagging.short.columns
    - tagging.short.features
    - tagging.short.split
    - tagging.short.threads
    - tagging.test.max_depth
    - tagging.test.random_state
    - tagging.test.sample
    - train.batch.columns
    - train.batch.dense
    - train.batch.epochs
    - train.batch.features
    - train.batch.random_state
    - train.dev.dense
    - train.dev.min_features
    - train.dev.num_est
    - train.dev.random_state
    - train.dev.threads
    - train.other.drop
    - train.other.max_features
    - train.other.min_features
    - train.other.trees
    - train.preset.epochs
    - train.preset.layers
    - train.preset.num_est
    - train.preset.passes
    - train.preset.random_state
    - train.preset.weight_factor
    - train.settings.drop
    - train.settings.layers
    - train.settings.learning_rate
    - train.settings.max_features
    - train.settings.weight_factor
    - train.short.columns
    - train.short.dense
    - train.short.tags
    - train.short.threads
    - train.test.features
    - train.test.layers
    - train.test.random_state
    - train.test.sample
    - train.test.split
    - train.test.threads
    - validation.batch.batch_size
    - validation.batch.epochs
    - validation.batch.estimators
    - validation.batch.learning_rate
    - validation.batch.min_features
    - validation.batch.split
    - validation.dev.columns
    - validation.dev.dense
    - validation.dev.drop
    - validation.dev.layers
    - validation.dev.min_features
    - validation.dev.trees
    - validation.other.min_features
    - validation.preset.batch_size
    - validation.preset.layers
    - validation.preset.max_depth
    - validation.preset.min_split
    - validation.preset.tags
    - validation.preset.trees
    - validation.preset.weight_factor
    - validation.settings.learning_rate
    - validation.short.drop
    - validation.short.max_depth
    - validation.short.sample
    - validation.test.epochs
    - validation.test.layers
    - validation.test.max_depth
    - variables.batch.passes
    - variables.batch.sample
    - variables.batch.threads
    - variables.batch.weight_factor
    - variables.dev.max_depth
    - variables.dev.num_est
    - variables.dev.trees
    - variables.other.drop
    - variables.other.features
    - variables.preset.batch_size
    - variables.preset.dense
    - variables.preset.drop
    - variables.preset.epochs
    - variables.preset.layers
    - variables.preset.learning_rate
    - variables.preset.num_est
    - variables.preset.passes
    - variables.settings.min_split
    - variables.settings.num_est
    - variables.settings.tags
    - variables.short.estimators
    - variables.short.learning_rate
    - variables.short.passes
    - variables.short.random_state
    - variables.test.columns
    - variables.test.epochs
    - variables.test.sample
    - variables.test.tags
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json users-test.csv
    deps:
    - evaluate.py
    - model.json
    - users-test.csv
    metrics:
    - metrics.json:
        cache: false
