stages:
  split:
    cmd: python split.py images.csv images-train.csv images-test.csv
    deps:
    - images.csv
    - split.py
    params:
    - prepare.classifier.dense
    - prepare.classifier.tags
    - prepare.classifier.weight_factor
    - prepare.diff.learning_rate
    - prepare.diff.max_depth
    - prepare.diff.min_features
    - prepare.diff.split
    - prepare.long.columns
    - prepare.long.features
    - prepare.long.layers
    - prepare.long.min_split
    - prepare.long.random_state
    - prepare.long.sample
    - prepare.other.batch_size
    - prepare.other.columns
    - prepare.other.drop
    - prepare.other.random_state
    - prepare.other.sample
    - prepare.other.split
    - prepare.preset.min_split
    - prepare.preset.seed
    - prepare.preset.trees
    - prepare.prod.batch_size
    - prepare.prod.estimators
    - prepare.prod.min_split
    - prepare.prod.seed
    - prepare.prod.split
    - prepare.prod.threads
    - prepare.rf.epochs
    - prepare.rf.ngrams
    outs:
    - images-test.csv
    - images-train.csv
  featurize:
    cmd: python featurize.py images-train.csv images-train-feats.csv
    deps:
    - featurize.py
    - images-train.csv
    params:
    - featurize.classifier.epochs
    - featurize.classifier.folds
    - featurize.classifier.min_features
    - featurize.classifier.seed
    - featurize.classifier.threads
    - featurize.diff.columns
    - featurize.diff.folds
    - featurize.diff.num_est
    - featurize.diff.seed
    - featurize.long.min_features
    - featurize.long.seed
    - featurize.long.split
    - featurize.long.threads
    - featurize.other.drop
    - featurize.other.learning_rate
    - featurize.preset.learning_rate
    - featurize.preset.max_depth
    - featurize.preset.max_features
    - featurize.preset.split
    - featurize.preset.tags
    - featurize.preset.weight_factor
    - featurize.prod.epochs
    - featurize.prod.features
    - featurize.prod.layers
    - featurize.prod.max_depth
    - featurize.prod.min_features
    - featurize.prod.min_split
    - featurize.prod.split
    - featurize.prod.threads
    - featurize.rf.batch_size
    - featurize.rf.columns
    - featurize.rf.dense
    - featurize.rf.drop
    - featurize.rf.max_features
    - featurize.rf.num_est
    - featurize.rf.trees
    outs:
    - images-train-feats.csv
  train:
    cmd: python train.py images-train-feats.csv model.json
    deps:
    - images-train-feats.csv
    - train.py
    params:
    - concurrent.classifier.learning_rate
    - concurrent.classifier.max_depth
    - concurrent.classifier.num_est
    - concurrent.classifier.passes
    - concurrent.classifier.threads
    - concurrent.diff.tags
    - concurrent.long.layers
    - concurrent.long.max_features
    - concurrent.long.weight_factor
    - concurrent.other.columns
    - concurrent.other.features
    - concurrent.other.passes
    - concurrent.other.random_state
    - concurrent.other.sample
    - concurrent.preset.columns
    - concurrent.preset.features
    - concurrent.preset.max_depth
    - concurrent.preset.min_split
    - concurrent.preset.sample
    - concurrent.prod.columns
    - concurrent.prod.dense
    - concurrent.prod.random_state
    - concurrent.prod.threads
    - concurrent.rf.min_features
    - concurrent.rf.random_state
    - model.classifier.max_depth
    - model.classifier.min_features
    - model.classifier.min_split
    - model.classifier.ngrams
    - model.diff.columns
    - model.diff.drop
    - model.diff.estimators
    - model.long.layers
    - model.long.seed
    - model.other.layers
    - model.other.tags
    - model.preset.estimators
    - model.preset.folds
    - model.preset.min_features
    - model.preset.random_state
    - model.preset.seed
    - model.preset.tags
    - model.prod.columns
    - model.prod.dense
    - model.prod.drop
    - model.prod.features
    - model.prod.max_features
    - model.prod.num_est
    - model.prod.random_state
    - model.prod.sample
    - model.rf.dense
    - model.rf.folds
    - model.rf.ngrams
    - model.rf.random_state
    - model.rf.weight_factor
    - preprocessing.diff.min_features
    - preprocessing.diff.random_state
    - preprocessing.diff.threads
    - preprocessing.diff.trees
    - preprocessing.long.estimators
    - preprocessing.long.layers
    - preprocessing.long.min_features
    - preprocessing.long.seed
    - preprocessing.other.columns
    - preprocessing.other.features
    - preprocessing.other.passes
    - preprocessing.other.random_state
    - preprocessing.other.threads
    - preprocessing.preset.epochs
    - preprocessing.preset.estimators
    - preprocessing.preset.seed
    - preprocessing.preset.split
    - preprocessing.prod.batch_size
    - preprocessing.prod.dense
    - preprocessing.prod.estimators
    - preprocessing.prod.folds
    - preprocessing.prod.max_depth
    - preprocessing.prod.max_features
    - preprocessing.prod.ngrams
    - preprocessing.prod.passes
    - preprocessing.prod.split
    - preprocessing.prod.trees
    - preprocessing.rf.columns
    - preprocessing.rf.min_features
    - preprocessing.rf.tags
    - settings.classifier.folds
    - settings.diff.drop
    - settings.diff.estimators
    - settings.diff.min_features
    - settings.diff.min_split
    - settings.long.epochs
    - settings.long.folds
    - settings.long.layers
    - settings.long.min_split
    - settings.other.learning_rate
    - settings.other.min_split
    - settings.preset.layers
    - settings.preset.learning_rate
    - settings.preset.passes
    - settings.prod.epochs
    - settings.prod.features
    - settings.prod.max_depth
    - settings.prod.ngrams
    - settings.prod.tags
    - settings.rf.dense
    - settings.rf.drop
    - settings.rf.max_depth
    - settings.rf.min_split
    - settings.rf.num_est
    - variables.classifier.columns
    - variables.classifier.folds
    - variables.classifier.layers
    - variables.classifier.ngrams
    - variables.classifier.random_state
    - variables.diff.estimators
    - variables.diff.max_depth
    - variables.diff.min_features
    - variables.diff.split
    - variables.diff.trees
    - variables.long.min_split
    - variables.long.num_est
    - variables.long.seed
    - variables.other.features
    - variables.other.min_split
    - variables.other.random_state
    - variables.other.threads
    - variables.other.trees
    - variables.preset.dense
    - variables.preset.layers
    - variables.preset.passes
    - variables.prod.seed
    - variables.rf.min_features
    - variables.rf.sample
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json images-test.csv
    deps:
    - evaluate.py
    - images-test.csv
    - model.json
    metrics:
    - metrics.json:
        cache: false
