model:
  preset:
    random_state: 603000000
    tags: 28
    min_features: 1050
    estimators: 98
    folds: 5
    seed: 707284539
  prod:
    columns: 30
    num_est: 164
    dense: 100
    sample: 0.38927
    random_state: 312000000
    max_features: 1750
    drop: 0.2
    features: 2740
  rf:
    folds: 6
    random_state: 222422383
    ngrams: 4
    dense: 400
    weight_factor: 0.3
  other:
    tags: 84
    layers: 1
  classifier:
    min_features: 1850
    min_split: 48
    ngrams: 2
    max_depth: 3
  diff:
    estimators: 157
    drop: 0.18772
    columns: 15
  long:
    layers: 2
    seed: 272372000
concurrent:
  rf:
    random_state: 653074762
    min_features: 1800
  preset:
    columns: 66
    max_depth: 9
    sample: 0.88258
    min_split: 16
    features: 2373
  other:
    passes: 34
    features: 3107
    columns: 79
    sample: 0.25
    random_state: 680288892
  diff:
    tags: 119
  prod:
    columns: 51
    threads: 30
    random_state: 640782289
    dense: 200
  classifier:
    learning_rate: 0.13807
    num_est: 24
    max_depth: 12
    passes: 104
    threads: 1
  long:
    layers: 2
    max_features: 2832
    weight_factor: 0.1
settings:
  rf:
    min_split: 64
    max_depth: 16
    dense: 300
    drop: 0.11444
    num_est: 250
  other:
    min_split: 32
    learning_rate: 0.16318
  preset:
    layers: 3
    learning_rate: 0.13
    passes: 52
  prod:
    epochs: 23
    ngrams: 4
    max_depth: 12
    features: 4610
    tags: 70
  long:
    folds: 5
    layers: 6
    min_split: 80
    epochs: 35
  diff:
    min_features: 3550
    min_split: 80
    drop: 0.1
    estimators: 104
  classifier:
    folds: 3
prepare:
  preset:
    min_split: 38
    trees: 30
    seed: 235048976
  prod:
    estimators: 271
    seed: 321086000
    split: 0.45088
    batch_size: 371
    threads: 16
    min_split: 62
  rf:
    ngrams: 3
    epochs: 45
  long:
    min_split: 36
    columns: 51
    sample: 1.06144
    random_state: 127790177
    layers: 5
    features: 2087
  other:
    sample: 0.77063
    drop: 0.0952
    columns: 11
    split: 0.37586
    batch_size: 576
    random_state: 385514060
  classifier:
    weight_factor: 0.35232
    dense: 242
    tags: 146
  diff:
    learning_rate: 0.13764
    max_depth: 3
    split: 0.54466
    min_features: 4307
preprocessing:
  prod:
    dense: 300
    max_features: 3450
    split: 0.3
    trees: 57
    max_depth: 16
    folds: 12
    batch_size: 176
    ngrams: 4
    passes: 104
    estimators: 234
  rf:
    min_features: 3700
    columns: 6
    tags: 28
  diff:
    threads: 28
    min_features: 4160
    random_state: 553000000
    trees: 78
  other:
    columns: 54
    threads: 15
    random_state: 191000000
    passes: 62
    features: 3222
  preset:
    epochs: 25
    split: 0.34353
    seed: 249776000
    estimators: 133
  long:
    estimators: 86
    seed: 425137941
    min_features: 1000
    layers: 2
variables:
  other:
    min_split: 80
    trees: 24
    threads: 15
    random_state: 762000000
    features: 3270
  diff:
    max_depth: 24
    trees: 83
    estimators: 146
    min_features: 4150
    split: 0.16914
  long:
    seed: 493427000
    num_est: 50
    min_split: 24
  classifier:
    random_state: 448420718
    ngrams: 6
    columns: 66
    layers: 6
    folds: 3
  preset:
    dense: 200
    passes: 52
    layers: 2
  rf:
    min_features: 1750
    sample: 0.52668
  prod:
    seed: 362728388
featurize:
  rf:
    dense: 81
    columns: 41
    max_features: 3259
    drop: 0.08146
    num_est: 120
    batch_size: 329
    trees: 57
  preset:
    max_features: 506
    split: 0.48956
    tags: 60
    weight_factor: 0.36444
    learning_rate: 0.04114
    max_depth: 24
  prod:
    max_depth: 23
    layers: 4
    threads: 20
    split: 0.53186
    epochs: 36
    min_split: 66
    features: 4087
    min_features: 4502
  long:
    seed: 1015120580
    split: 0.35932
    threads: 6
    min_features: 3100
  classifier:
    seed: 1045197566
    folds: 3
    min_features: 3358
    threads: 32
    epochs: 22
  diff:
    folds: 6
    columns: 6
    num_est: 145
    seed: 193096920
  other:
    drop: 0.21938
    learning_rate: 0.02
