concurrent:
  batch:
    tags: 63
    epochs: 55
    features: 960
    batch_size: 704
  short:
    max_features: 5108
    folds: 9
  selection:
    random_state: 304000000
    epochs: 88
    max_depth: 16
    num_est: 166
    folds: 5
    split: 0.49188
  rf:
    weight_factor: 0.09449
    columns: 2
    passes: 20
    estimators: 182
  collection:
    ngrams: 2
    max_depth: 16
    threads: 3
    min_split: 19
    weight_factor: 0.33961
  other:
    num_est: 150
    dense: 93
    batch_size: 14
  prod:
    folds: 3
    sample: 0.59213
model:
  collection:
    tags: 63
    num_est: 110
  rf:
    ngrams: 4
    drop: 0.09169
    estimators: 121
    min_split: 26
    batch_size: 557
  other:
    random_state: 676000000
    max_features: 5311
    seed: 528465684
  prod:
    num_est: 203
    epochs: 40
    ngrams: 9
    split: 0.4
  selection:
    layers: 2
    batch_size: 352
    learning_rate: 0.16522
    max_features: 1270
  batch:
    ngrams: 1
    max_depth: 35
prepare:
  short:
    epochs: 33
    learning_rate: 0.13541
    features: 4032
    min_split: 68
  batch:
    layers: 4
    epochs: 56
    features: 292
    min_split: 32
  collection:
    passes: 93
    seed: 830542176
    drop: 0.44012
    max_features: 1420
    estimators: 252
  rf:
    features: 1778
    num_est: 122
  prod:
    weight_factor: 0.21475
    drop: 0.3433
    epochs: 81
    folds: 6
    max_features: 493
    columns: 40
  other:
    random_state: 541985117
    min_features: 4066
    columns: 49
    batch_size: 784
    trees: 2
  selection:
    weight_factor: 0.30516
validation:
  prod:
    layers: 2
    max_depth: 17
    folds: 7
  collection:
    passes: 52
    layers: 1
    weight_factor: 0.2
  rf:
    ngrams: 1
    dense: 300
    trees: 18
    split: 0.29192
    features: 1076
    min_split: 17
  short:
    max_depth: 13
    tags: 126
    folds: 6
    split: 0.2
  other:
    learning_rate: 0.12
    max_features: 941
    tags: 84
    min_features: 1150
  batch:
    max_features: 934
    learning_rate: 0.15
    split: 0.48604
    passes: 32
  selection:
    sample: 0.53937
preprocessing:
  collection:
    sample: 0.75
    layers: 6
  rf:
    tags: 98
    weight_factor: 0.18628
    split: 0.52931
    passes: 72
  selection:
    columns: 78
    max_features: 5000
    dense: 473
    sample: 0.42256
    batch_size: 560
  other:
    learning_rate: 0.05786
    min_features: 3480
  short:
    columns: 67
    trees: 52
    estimators: 54
  prod:
    max_features: 211
    weight_factor: 0.0782
    passes: 5
variables:
  short:
    min_features: 2250
    ngrams: 6
    folds: 6
  batch:
    epochs: 11
    threads: 26
  other:
    ngrams: 6
    dense: 306
  collection:
    seed: 1005929556
  prod:
    epochs: 45
    learning_rate: 0.12
    tags: 92
  selection:
    threads: 21
    features: 1700
    split: 0.1
  rf:
    threads: 5
    weight_factor: 0.2
settings:
  selection:
    dense: 400
    trees: 72
    seed: 745509000
    passes: 15
    max_depth: 30
  prod:
    min_features: 3301
    columns: 38
  rf:
    max_depth: 12
  collection:
    weight_factor: 0.27139
  batch:
    num_est: 197
    estimators: 35
  other:
    folds: 3
  short:
    ngrams: 3
