concurrent:
  batch:
    tags: 63
    epochs: 55
    features: 960
    batch_size: 704
  short:
    max_features: 5108
    folds: 9
  selection:
    random_state: 304000000
    epochs: 88
    max_depth: 16
    num_est: 150
    folds: 6
    split: 0.4
  rf:
    weight_factor: 0.09449
    columns: 2
    passes: 20
    estimators: 232
  collection:
    ngrams: 2
    max_depth: 16
    threads: 3
    min_split: 16
    weight_factor: 0.33961
  other:
    num_est: 150
    dense: 93
    batch_size: 14
  prod:
    folds: 3
    sample: 0.59213
model:
  collection:
    tags: 63
    num_est: 110
  rf:
    ngrams: 4
    drop: 0.09169
    estimators: 121
    min_split: 26
    batch_size: 557
  other:
    random_state: 676000000
    max_features: 6150
    seed: 528465684
  prod:
    num_est: 203
    epochs: 40
    ngrams: 9
    split: 0.4
  selection:
    layers: 2
    batch_size: 352
    learning_rate: 0.12462
    max_features: 1150
  batch:
    ngrams: 1
    max_depth: 35
prepare:
  short:
    epochs: 33
    learning_rate: 0.13541
    features: 4032
    min_split: 68
  batch:
    layers: 3
    epochs: 56
    features: 284
    min_split: 28
  collection:
    passes: 93
    seed: 830542176
    drop: 0.49047
    max_features: 979
    estimators: 260
  rf:
    features: 1834
    num_est: 111
  prod:
    weight_factor: 0.21475
    drop: 0.49255
    epochs: 53
    folds: 6
    max_features: 493
    columns: 32
  other:
    random_state: 655902915
    min_features: 4066
    columns: 49
    batch_size: 611
    trees: 2
  selection:
    weight_factor: 0.30516
validation:
  prod:
    layers: 2
    max_depth: 17
    folds: 9
  collection:
    passes: 52
    layers: 1
    weight_factor: 0.2
  rf:
    ngrams: 2
    dense: 300
    trees: 18
    split: 0.29192
    features: 1076
    min_split: 17
  short:
    max_depth: 12
    tags: 126
    folds: 6
    split: 0.2
  other:
    learning_rate: 0.12
    max_features: 1200
    tags: 77
    min_features: 1150
  batch:
    max_features: 934
    learning_rate: 0.15
    split: 0.48604
    passes: 32
  selection:
    sample: 0.5
preprocessing:
  collection:
    sample: 0.75
    layers: 6
  rf:
    tags: 98
    weight_factor: 0.2
    split: 0.56745
    passes: 72
  selection:
    columns: 78
    max_features: 5000
    dense: 473
    sample: 0.42256
    batch_size: 560
  other:
    learning_rate: 0.05786
    min_features: 3480
  short:
    columns: 67
    trees: 52
    estimators: 54
  prod:
    max_features: 200
    weight_factor: 0.0782
    passes: 5
variables:
  short:
    min_features: 2250
    ngrams: 6
    folds: 6
  batch:
    epochs: 11
    threads: 28
  other:
    ngrams: 6
    dense: 306
  collection:
    seed: 831947000
  prod:
    epochs: 45
    learning_rate: 0.12
    tags: 96
  selection:
    threads: 23
    features: 1700
    split: 0.1
  rf:
    threads: 5
    weight_factor: 0.2
settings:
  selection:
    dense: 400
    trees: 72
    seed: 745509000
    passes: 14
    max_depth: 28
  prod:
    min_features: 3216
    columns: 38
  rf:
    max_depth: 12
  collection:
    weight_factor: 0.30412
  batch:
    num_est: 197
    estimators: 35
  other:
    folds: 3
  short:
    ngrams: 3
