concurrent:
  batch:
    tags: 65
    epochs: 51
    features: 772
    batch_size: 704
  short:
    max_features: 4588
    folds: 6
  selection:
    random_state: 304000000
    epochs: 84
    max_depth: 19
    num_est: 172
    folds: 5
    split: 0.44902
  rf:
    weight_factor: 0.08532
    columns: 2
    passes: 20
    estimators: 182
  collection:
    ngrams: 2
    max_depth: 16
    threads: 3
    min_split: 19
    weight_factor: 0.33961
  other:
    num_est: 150
    dense: 93
    batch_size: 14
  prod:
    folds: 3
    sample: 0.59213
model:
  collection:
    tags: 50
    num_est: 110
  rf:
    ngrams: 4
    drop: 0.09169
    estimators: 121
    min_split: 26
    batch_size: 557
  other:
    random_state: 585943185
    max_features: 3823
    seed: 528465684
  prod:
    num_est: 203
    epochs: 40
    ngrams: 9
    split: 0.49509
  selection:
    layers: 1
    batch_size: 330
    learning_rate: 0.16522
    max_features: 1298
  batch:
    ngrams: 1
    max_depth: 35
prepare:
  short:
    epochs: 47
    learning_rate: 0.0885
    features: 3871
    min_split: 64
  batch:
    layers: 4
    epochs: 90
    features: 305
    min_split: 27
  collection:
    passes: 77
    seed: 716354641
    drop: 0.40417
    max_features: 1006
    estimators: 280
  rf:
    features: 2612
    num_est: 100
  prod:
    weight_factor: 0.23825
    drop: 0.45495
    epochs: 75
    folds: 6
    max_features: 389
    columns: 31
  other:
    random_state: 658353191
    min_features: 4275
    columns: 61
    batch_size: 613
    trees: 3
  selection:
    weight_factor: 0.30823
validation:
  prod:
    layers: 1
    max_depth: 19
    folds: 8
  collection:
    passes: 52
    layers: 1
    weight_factor: 0.2
  rf:
    ngrams: 1
    dense: 316
    trees: 18
    split: 0.29192
    features: 1076
    min_split: 17
  short:
    max_depth: 13
    tags: 146
    folds: 6
    split: 0.21611
  other:
    learning_rate: 0.12
    max_features: 941
    tags: 87
    min_features: 1150
  batch:
    max_features: 934
    learning_rate: 0.15
    split: 0.48604
    passes: 32
  selection:
    sample: 0.47276
preprocessing:
  collection:
    sample: 0.79877
    layers: 6
  rf:
    tags: 98
    weight_factor: 0.20387
    split: 0.52931
    passes: 91
  selection:
    columns: 81
    max_features: 5000
    dense: 473
    sample: 0.61465
    batch_size: 666
  other:
    learning_rate: 0.05786
    min_features: 2699
  short:
    columns: 67
    trees: 54
    estimators: 54
  prod:
    max_features: 180
    weight_factor: 0.0782
    passes: 7
variables:
  short:
    min_features: 2750
    ngrams: 4
    folds: 6
  batch:
    epochs: 10
    threads: 26
  other:
    ngrams: 6
    dense: 360
  collection:
    seed: 1019950104
  prod:
    epochs: 44
    learning_rate: 0.1168
    tags: 92
  selection:
    threads: 21
    features: 1700
    split: 0.1
  rf:
    threads: 5
    weight_factor: 0.19397
settings:
  selection:
    dense: 400
    trees: 56
    seed: 710513101
    passes: 16
    max_depth: 30
  prod:
    min_features: 2880
    columns: 38
  rf:
    max_depth: 12
  collection:
    weight_factor: 0.27139
  batch:
    num_est: 197
    estimators: 35
  other:
    folds: 3
  short:
    ngrams: 4
