stages:
  split:
    cmd: python split.py events.csv events-train.csv events-test.csv
    deps:
    - events.csv
    - split.py
    params:
    - prepare.auto.min_split
    - prepare.auto.num_est
    - prepare.auto.passes
    - prepare.combine.min_features
    - prepare.combine.num_est
    - prepare.combine.passes
    - prepare.combine.sample
    - prepare.combine.tags
    - prepare.combine.trees
    - prepare.diff.dense
    - prepare.diff.layers
    - prepare.diff.max_features
    - prepare.diff.passes
    - prepare.diff.tags
    - prepare.diff.trees
    - prepare.long.columns
    - prepare.long.trees
    - prepare.other.dense
    - prepare.other.layers
    - prepare.other.learning_rate
    - prepare.other.random_state
    - prepare.other.split
    - prepare.other.tags
    - prepare.preset.batch_size
    - prepare.preset.columns
    - prepare.preset.passes
    - prepare.preset.split
    - prepare.preset.tags
    - prepare.preset.trees
    - prepare.short.layers
    - prepare.short.learning_rate
    - prepare.short.num_est
    - prepare.short.sample
    - prepare.short.split
    - prepare.short.trees
    - prepare.short.weight_factor
    outs:
    - events-test.csv
    - events-train.csv
  featurize:
    cmd: python featurize.py events-train.csv events-train-feats.csv
    deps:
    - events-train.csv
    - featurize.py
    params:
    - featurize.auto.max_features
    - featurize.auto.ngrams
    - featurize.combine.batch_size
    - featurize.combine.max_depth
    - featurize.combine.max_features
    - featurize.combine.sample
    - featurize.diff.estimators
    - featurize.diff.layers
    - featurize.diff.max_depth
    - featurize.diff.max_features
    - featurize.long.folds
    - featurize.long.learning_rate
    - featurize.long.min_features
    - featurize.long.random_state
    - featurize.long.tags
    - featurize.other.drop
    - featurize.other.layers
    - featurize.other.max_features
    - featurize.other.passes
    - featurize.other.tags
    - featurize.other.weight_factor
    - featurize.short.columns
    - featurize.short.dense
    - featurize.short.epochs
    - featurize.short.estimators
    - featurize.short.layers
    - featurize.short.max_depth
    - featurize.short.min_features
    - featurize.short.num_est
    outs:
    - events-train-feats.csv
  train:
    cmd: python train.py events-train-feats.csv model.json
    deps:
    - events-train-feats.csv
    - train.py
    params:
    - concurrent.auto.batch_size
    - concurrent.auto.features
    - concurrent.auto.random_state
    - concurrent.auto.tags
    - concurrent.combine.dense
    - concurrent.combine.drop
    - concurrent.combine.min_features
    - concurrent.combine.min_split
    - concurrent.combine.split
    - concurrent.combine.trees
    - concurrent.combine.weight_factor
    - concurrent.diff.folds
    - concurrent.diff.layers
    - concurrent.diff.random_state
    - concurrent.diff.weight_factor
    - concurrent.long.seed
    - concurrent.long.weight_factor
    - concurrent.other.batch_size
    - concurrent.other.layers
    - concurrent.other.learning_rate
    - concurrent.other.max_features
    - concurrent.other.min_features
    - concurrent.other.min_split
    - concurrent.other.passes
    - concurrent.other.seed
    - concurrent.other.tags
    - concurrent.other.threads
    - concurrent.preset.columns
    - concurrent.preset.estimators
    - concurrent.preset.folds
    - concurrent.preset.max_depth
    - concurrent.preset.ngrams
    - concurrent.preset.num_est
    - concurrent.short.columns
    - concurrent.short.sample
    - concurrent.short.seed
    - model.auto.epochs
    - model.auto.layers
    - model.auto.max_features
    - model.combine.columns
    - model.combine.drop
    - model.combine.estimators
    - model.combine.min_features
    - model.combine.tags
    - model.combine.threads
    - model.diff.epochs
    - model.diff.estimators
    - model.diff.max_depth
    - model.diff.num_est
    - model.diff.threads
    - model.long.columns
    - model.long.estimators
    - model.long.folds
    - model.long.learning_rate
    - model.long.min_split
    - model.long.ngrams
    - model.long.passes
    - model.long.threads
    - model.long.trees
    - model.other.columns
    - model.other.estimators
    - model.other.layers
    - model.other.min_features
    - model.other.sample
    - model.preset.batch_size
    - model.short.batch_size
    - model.short.dense
    - model.short.num_est
    - model.short.random_state
    - model.short.seed
    - model.short.split
    - model.short.tags
    - settings.auto.tags
    - settings.auto.weight_factor
    - settings.combine.epochs
    - settings.combine.folds
    - settings.combine.min_split
    - settings.combine.split
    - settings.combine.weight_factor
    - settings.diff.columns
    - settings.diff.epochs
    - settings.diff.folds
    - settings.diff.min_split
    - settings.diff.sample
    - settings.long.drop
    - settings.long.epochs
    - settings.long.folds
    - settings.long.min_split
    - settings.long.num_est
    - settings.long.passes
    - settings.other.estimators
    - settings.other.max_depth
    - settings.other.max_features
    - settings.other.passes
    - settings.other.random_state
    - settings.other.tags
    - settings.other.trees
    - settings.preset.epochs
    - settings.preset.learning_rate
    - settings.short.columns
    - settings.short.max_depth
    - settings.short.ngrams
    - settings.short.passes
    - settings.short.random_state
    - train.auto.columns
    - train.auto.epochs
    - train.auto.sample
    - train.combine.estimators
    - train.combine.min_split
    - train.combine.ngrams
    - train.combine.sample
    - train.combine.seed
    - train.combine.split
    - train.combine.threads
    - train.diff.batch_size
    - train.diff.dense
    - train.diff.epochs
    - train.diff.estimators
    - train.diff.features
    - train.diff.learning_rate
    - train.diff.max_features
    - train.diff.ngrams
    - train.diff.random_state
    - train.diff.tags
    - train.long.random_state
    - train.long.seed
    - train.other.columns
    - train.other.drop
    - train.other.epochs
    - train.other.estimators
    - train.other.sample
    - train.other.tags
    - train.other.trees
    - train.preset.drop
    - train.preset.features
    - train.preset.learning_rate
    - train.short.columns
    - train.short.folds
    - train.short.num_est
    - variables.auto.dense
    - variables.auto.layers
    - variables.auto.max_depth
    - variables.auto.tags
    - variables.combine.epochs
    - variables.combine.learning_rate
    - variables.combine.num_est
    - variables.combine.random_state
    - variables.combine.tags
    - variables.diff.epochs
    - variables.diff.ngrams
    - variables.diff.sample
    - variables.long.estimators
    - variables.long.min_features
    - variables.long.tags
    - variables.long.weight_factor
    - variables.other.dense
    - variables.other.drop
    - variables.other.layers
    - variables.other.seed
    - variables.other.weight_factor
    - variables.preset.estimators
    - variables.preset.min_features
    - variables.short.folds
    - variables.short.learning_rate
    - variables.short.min_features
    - variables.short.num_est
    - variables.short.seed
    - variables.short.tags
    - variables.short.trees
    - variables.short.weight_factor
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json events-test.csv
    deps:
    - evaluate.py
    - events-test.csv
    - model.json
    metrics:
    - metrics.json:
        cache: false
