model:
  preset:
    batch_size: 350
  other:
    estimators: 194
    sample: 0.37966
    min_features: 1266
    columns: 60
    layers: 6
  combine:
    tags: 42
    min_features: 3839
    threads: 15
    estimators: 70
    drop: 0.4
    columns: 48
  long:
    passes: 42
    trees: 51
    learning_rate: 0.0762
    ngrams: 6
    estimators: 34
    folds: 2
    columns: 37
    min_split: 45
    threads: 2
  diff:
    estimators: 126
    threads: 16
    num_est: 87
    epochs: 86
    max_depth: 30
  short:
    num_est: 75
    seed: 854370000
    dense: 500
    batch_size: 768
    tags: 93
    random_state: 156566786
    split: 0.23202
  auto:
    epochs: 10
    layers: 2
    max_features: 2890
settings:
  long:
    min_split: 61
    num_est: 225
    drop: 0.18086
    epochs: 58
    passes: 59
    folds: 3
  short:
    max_depth: 8
    ngrams: 3
    random_state: 590000000
    passes: 66
    columns: 35
  combine:
    epochs: 8
    weight_factor: 0.2
    folds: 3
    min_split: 47
    split: 0.3
  preset:
    learning_rate: 0.04
    epochs: 10
  other:
    max_depth: 32
    max_features: 2531
    tags: 108
    random_state: 90000000
    trees: 43
    estimators: 31
    passes: 38
  diff:
    folds: 5
    sample: 0.25
    columns: 22
    epochs: 9
    min_split: 31
  auto:
    weight_factor: 0.2
    tags: 126
prepare:
  short:
    num_est: 209
    weight_factor: 0.15957
    sample: 0.22684
    learning_rate: 0.08324
    split: 0.33122
    layers: 2
    trees: 86
  preset:
    trees: 67
    split: 0.23267
    columns: 39
    passes: 60
    batch_size: 99
    tags: 78
  combine:
    passes: 48
    min_features: 2079
    sample: 0.31037
    trees: 10
    num_est: 243
    tags: 104
  diff:
    tags: 33
    trees: 56
    layers: 2
    passes: 56
    dense: 106
    max_features: 75
  long:
    columns: 16
    trees: 47
  auto:
    num_est: 221
    min_split: 42
    passes: 29
  other:
    tags: 151
    split: 0.23789
    dense: 555
    random_state: 239319467
    learning_rate: 0.06037
    layers: 5
concurrent:
  long:
    seed: 355944054
    weight_factor: 0.24572
  auto:
    batch_size: 224
    random_state: 528000000
    features: 5989
    tags: 14
  other:
    min_features: 1773
    max_features: 4500
    min_split: 48
    batch_size: 581
    seed: 788703861
    learning_rate: 0.05
    layers: 3
    tags: 68
    threads: 3
    passes: 70
  preset:
    max_depth: 9
    num_est: 225
    estimators: 56
    columns: 62
    ngrams: 6
    folds: 14
  combine:
    trees: 43
    dense: 400
    drop: 0.4
    split: 0.08234
    weight_factor: 0.32452
    min_features: 600
    min_split: 35
  short:
    sample: 0.49053
    columns: 6
    seed: 404629015
  diff:
    weight_factor: 0.10193
    random_state: 263000000
    folds: 3
    layers: 2
featurize:
  other:
    layers: 7
    passes: 45
    weight_factor: 0.23946
    drop: 0.15879
    max_features: 5009
    tags: 96
  short:
    min_features: 849
    layers: 4
    max_depth: 13
    num_est: 106
    estimators: 118
    dense: 153
    epochs: 42
    columns: 27
  diff:
    estimators: 46
    layers: 3
    max_depth: 14
    max_features: 3709
  long:
    tags: 66
    min_features: 2618
    learning_rate: 0.07304
    folds: 7
    random_state: 71987481
  auto:
    max_features: 3662
    ngrams: 2
  combine:
    batch_size: 471
    sample: 0.51222
    max_depth: 10
    max_features: 588
train:
  auto:
    epochs: 18
    columns: 63
    sample: 0.87595
  other:
    columns: 75
    trees: 54
    epochs: 70
    sample: 0.25
    drop: 0.2
    tags: 103
    estimators: 209
  diff:
    dense: 184
    learning_rate: 0.13519
    ngrams: 8
    tags: 55
    batch_size: 657
    estimators: 151
    random_state: 547792852
    max_features: 1563
    epochs: 15
    features: 3530
  combine:
    threads: 10
    ngrams: 6
    min_split: 91
    seed: 351561583
    split: 0.4
    sample: 0.57637
    estimators: 212
  preset:
    learning_rate: 0.14
    features: 2077
    drop: 0.11893
  short:
    columns: 64
    num_est: 250
    folds: 3
  long:
    random_state: 632000000
    seed: 497805221
variables:
  other:
    drop: 0.19942
    dense: 248
    weight_factor: 0.36167
    seed: 835280000
    layers: 3
  short:
    min_features: 3850
    weight_factor: 0.10787
    tags: 7
    trees: 69
    num_est: 172
    learning_rate: 0.13
    folds: 9
    seed: 126530000
  combine:
    num_est: 122
    tags: 79
    random_state: 3026183
    learning_rate: 0.09
    epochs: 5
  long:
    estimators: 197
    weight_factor: 0.26779
    tags: 21
    min_features: 3300
  auto:
    tags: 49
    layers: 6
    dense: 466
    max_depth: 16
  preset:
    estimators: 158
    min_features: 1550
  diff:
    sample: 0.25445
    epochs: 46
    ngrams: 2
