model:
  preset:
    batch_size: 320
  other:
    estimators: 147
    sample: 0.5
    min_features: 1148
    columns: 60
    layers: 6
  combine:
    tags: 42
    min_features: 4350
    threads: 15
    estimators: 61
    drop: 0.4
    columns: 48
  long:
    passes: 56
    trees: 51
    learning_rate: 0.0762
    ngrams: 6
    estimators: 34
    folds: 3
    columns: 52
    min_split: 48
    threads: 2
  diff:
    estimators: 126
    threads: 16
    num_est: 87
    epochs: 57
    max_depth: 30
  short:
    num_est: 75
    seed: 854370000
    dense: 500
    batch_size: 768
    tags: 93
    random_state: 112483395
    split: 0.23202
  auto:
    epochs: 10
    layers: 2
    max_features: 2890
settings:
  long:
    min_split: 61
    num_est: 225
    drop: 0.2
    epochs: 70
    passes: 48
    folds: 3
  short:
    max_depth: 8
    ngrams: 3
    random_state: 590000000
    passes: 66
    columns: 35
  combine:
    epochs: 8
    weight_factor: 0.2
    folds: 3
    min_split: 40
    split: 0.3
  preset:
    learning_rate: 0.04
    epochs: 10
  other:
    max_depth: 32
    max_features: 2531
    tags: 108
    random_state: 90000000
    trees: 43
    estimators: 31
    passes: 38
  diff:
    folds: 5
    sample: 0.25
    columns: 22
    epochs: 9
    min_split: 31
  auto:
    weight_factor: 0.2
    tags: 126
prepare:
  short:
    num_est: 209
    weight_factor: 0.18042
    sample: 0.2049
    learning_rate: 0.08324
    split: 0.33122
    layers: 2
    trees: 86
  preset:
    trees: 67
    split: 0.23267
    columns: 33
    passes: 60
    batch_size: 99
    tags: 57
  combine:
    passes: 48
    min_features: 2079
    sample: 0.22072
    trees: 10
    num_est: 243
    tags: 104
  diff:
    tags: 35
    trees: 56
    layers: 1
    passes: 56
    dense: 108
    max_features: 75
  long:
    columns: 12
    trees: 47
  auto:
    num_est: 227
    min_split: 42
    passes: 19
  other:
    tags: 151
    split: 0.23789
    dense: 409
    random_state: 314384422
    learning_rate: 0.06554
    layers: 4
concurrent:
  long:
    seed: 355944054
    weight_factor: 0.24572
  auto:
    batch_size: 224
    random_state: 528000000
    features: 5989
    tags: 14
  other:
    min_features: 1648
    max_features: 4500
    min_split: 48
    batch_size: 881
    seed: 611752287
    learning_rate: 0.05
    layers: 3
    tags: 63
    threads: 3
    passes: 70
  preset:
    max_depth: 9
    num_est: 225
    estimators: 68
    columns: 82
    ngrams: 6
    folds: 14
  combine:
    trees: 43
    dense: 400
    drop: 0.4
    split: 0.08234
    weight_factor: 0.32452
    min_features: 600
    min_split: 35
  short:
    sample: 0.49053
    columns: 6
    seed: 521986000
  diff:
    weight_factor: 0.1
    random_state: 263000000
    folds: 3
    layers: 2
featurize:
  other:
    layers: 6
    passes: 45
    weight_factor: 0.23946
    drop: 0.15879
    max_features: 5009
    tags: 84
  short:
    min_features: 918
    layers: 4
    max_depth: 18
    num_est: 106
    estimators: 118
    dense: 209
    epochs: 30
    columns: 27
  diff:
    estimators: 41
    layers: 4
    max_depth: 14
    max_features: 3709
  long:
    tags: 59
    min_features: 1980
    learning_rate: 0.07304
    folds: 7
    random_state: 71987481
  auto:
    max_features: 3662
    ngrams: 2
  combine:
    batch_size: 348
    sample: 0.39502
    max_depth: 12
    max_features: 507
train:
  auto:
    epochs: 19
    columns: 63
    sample: 0.87595
  other:
    columns: 75
    trees: 54
    epochs: 70
    sample: 0.25
    drop: 0.2
    tags: 103
    estimators: 209
  diff:
    dense: 184
    learning_rate: 0.13519
    ngrams: 8
    tags: 58
    batch_size: 657
    estimators: 151
    random_state: 663000000
    max_features: 1563
    epochs: 15
    features: 3530
  combine:
    threads: 10
    ngrams: 6
    min_split: 91
    seed: 283202762
    split: 0.4
    sample: 0.57637
    estimators: 212
  preset:
    learning_rate: 0.14
    features: 2077
    drop: 0.11893
  short:
    columns: 64
    num_est: 250
    folds: 3
  long:
    random_state: 632000000
    seed: 497805221
variables:
  other:
    drop: 0.19942
    dense: 248
    weight_factor: 0.36167
    seed: 835280000
    layers: 4
  short:
    min_features: 3850
    weight_factor: 0.10787
    tags: 7
    trees: 69
    num_est: 172
    learning_rate: 0.11
    folds: 9
    seed: 126530000
  combine:
    num_est: 102
    tags: 79
    random_state: 3026183
    learning_rate: 0.09
    epochs: 5
  long:
    estimators: 197
    weight_factor: 0.27018
    tags: 21
    min_features: 3300
  auto:
    tags: 49
    layers: 6
    dense: 400
    max_depth: 16
  preset:
    estimators: 158
    min_features: 1550
  diff:
    sample: 0.25445
    epochs: 46
    ngrams: 2
