model:
  preset:
    batch_size: 320
  other:
    estimators: 175
    sample: 0.5
    min_features: 1100
    columns: 60
    layers: 6
  combine:
    tags: 42
    min_features: 4350
    threads: 13
    estimators: 61
    drop: 0.4
    columns: 39
  long:
    passes: 56
    trees: 54
    learning_rate: 0.09
    ngrams: 6
    estimators: 41
    folds: 3
    columns: 42
    min_split: 48
    threads: 3
  diff:
    estimators: 126
    threads: 15
    num_est: 75
    epochs: 70
    max_depth: 24
  short:
    num_est: 75
    seed: 854370000
    dense: 500
    batch_size: 768
    tags: 112
    random_state: 112483395
    split: 0.2
  auto:
    epochs: 11
    layers: 2
    max_features: 2400
settings:
  long:
    min_split: 80
    num_est: 225
    drop: 0.2
    epochs: 70
    passes: 54
    folds: 3
  short:
    max_depth: 8
    ngrams: 3
    random_state: 590000000
    passes: 66
    columns: 45
  combine:
    epochs: 10
    weight_factor: 0.2
    folds: 3
    min_split: 48
    split: 0.3
  preset:
    learning_rate: 0.04
    epochs: 10
  other:
    max_depth: 32
    max_features: 2531
    tags: 108
    random_state: 90000000
    trees: 57
    estimators: 31
    passes: 38
  diff:
    folds: 6
    sample: 0.25
    columns: 22
    epochs: 10
    min_split: 32
  auto:
    weight_factor: 0.2
    tags: 126
prepare:
  short:
    num_est: 219
    weight_factor: 0.18042
    sample: 0.2049
    learning_rate: 0.08
    split: 0.33122
    layers: 2
    trees: 72
  preset:
    trees: 65
    split: 0.2
    columns: 33
    passes: 52
    batch_size: 99
    tags: 68
  combine:
    passes: 48
    min_features: 1831
    sample: 0.21203
    trees: 9
    num_est: 209
    tags: 131
  diff:
    tags: 45
    trees: 70
    layers: 2
    passes: 41
    dense: 92
    max_features: 75
  long:
    columns: 13
    trees: 40
  auto:
    num_est: 181
    min_split: 42
    passes: 24
  other:
    tags: 108
    split: 0.23789
    dense: 452
    random_state: 300000000
    learning_rate: 0.06554
    layers: 5
concurrent:
  long:
    seed: 323673000
    weight_factor: 0.3
  auto:
    batch_size: 224
    random_state: 528000000
    features: 5989
    tags: 11
  other:
    min_features: 2041
    max_features: 4500
    min_split: 48
    batch_size: 720
    seed: 611752287
    learning_rate: 0.05
    layers: 3
    tags: 63
    threads: 3
    passes: 70
  preset:
    max_depth: 9
    num_est: 225
    estimators: 68
    columns: 82
    ngrams: 6
    folds: 14
  combine:
    trees: 57
    dense: 400
    drop: 0.4
    split: 0.1
    weight_factor: 0.3
    min_features: 600
    min_split: 32
  short:
    sample: 0.5
    columns: 6
    seed: 521986000
  diff:
    weight_factor: 0.1
    random_state: 263000000
    folds: 3
    layers: 2
featurize:
  other:
    layers: 6
    passes: 36
    weight_factor: 0.18438
    drop: 0.22292
    max_features: 5286
    tags: 84
  short:
    min_features: 1076
    layers: 4
    max_depth: 14
    num_est: 111
    estimators: 108
    dense: 200
    epochs: 30
    columns: 37
  diff:
    estimators: 44
    layers: 4
    max_depth: 12
    max_features: 2555
  long:
    tags: 63
    min_features: 2350
    learning_rate: 0.09693
    folds: 7
    random_state: 77777188
  auto:
    max_features: 4174
    ngrams: 2
  combine:
    batch_size: 444
    sample: 0.52719
    max_depth: 12
    max_features: 454
train:
  auto:
    epochs: 20
    columns: 63
    sample: 0.74752
  other:
    columns: 75
    trees: 54
    epochs: 70
    sample: 0.25
    drop: 0.2
    tags: 103
    estimators: 209
  diff:
    dense: 200
    learning_rate: 0.15
    ngrams: 8
    tags: 63
    batch_size: 672
    estimators: 151
    random_state: 663000000
    max_features: 1600
    epochs: 15
    features: 3530
  combine:
    threads: 11
    ngrams: 6
    min_split: 80
    seed: 288097000
    split: 0.4
    sample: 0.5
    estimators: 212
  preset:
    learning_rate: 0.14
    features: 2740
    drop: 0.11893
  short:
    columns: 64
    num_est: 250
    folds: 3
  long:
    random_state: 632000000
    seed: 640147000
variables:
  other:
    drop: 0.2
    dense: 300
    weight_factor: 0.3
    seed: 835280000
    layers: 4
  short:
    min_features: 4956
    weight_factor: 0.08205
    tags: 7
    trees: 57
    num_est: 175
    learning_rate: 0.11
    folds: 9
    seed: 126530000
  combine:
    num_est: 100
    tags: 81
    random_state: 4000000
    learning_rate: 0.09
    epochs: 5
  long:
    estimators: 197
    weight_factor: 0.27018
    tags: 21
    min_features: 3300
  auto:
    tags: 49
    layers: 6
    dense: 400
    max_depth: 16
  preset:
    estimators: 158
    min_features: 1550
  diff:
    sample: 0.25
    epochs: 45
    ngrams: 2
