stages:
  split:
    cmd: python split.py users.csv users-train.csv users-test.csv
    deps:
    - split.py
    - users.csv
    params:
    - prepare.batch.features
    - prepare.batch.learning_rate
    - prepare.batch.min_split
    - prepare.batch.ngrams
    - prepare.batch.split
    - prepare.classifier.columns
    - prepare.classifier.features
    - prepare.classifier.split
    - prepare.dev.batch_size
    - prepare.dev.columns
    - prepare.dev.epochs
    - prepare.dev.features
    - prepare.dev.max_features
    - prepare.dev.sample
    - prepare.dev.seed
    - prepare.dev.tags
    - prepare.dev.trees
    - prepare.dev.weight_factor
    - prepare.other.drop
    - prepare.other.epochs
    - prepare.other.features
    - prepare.other.folds
    - prepare.other.ngrams
    - prepare.other.num_est
    - prepare.requests.features
    - prepare.requests.folds
    - prepare.requests.split
    - prepare.rf.columns
    - prepare.rf.epochs
    - prepare.rf.layers
    - prepare.rf.num_est
    - prepare.rf.passes
    - prepare.rf.random_state
    - prepare.selection.features
    - prepare.selection.layers
    - prepare.selection.ngrams
    - prepare.selection.passes
    - prepare.selection.seed
    - prepare.selection.split
    outs:
    - users-test.csv
    - users-train.csv
  featurize:
    cmd: python featurize.py users-train.csv users-train-feats.csv
    deps:
    - featurize.py
    - users-train.csv
    params:
    - featurize.batch.batch_size
    - featurize.batch.max_features
    - featurize.batch.threads
    - featurize.batch.weight_factor
    - featurize.classifier.batch_size
    - featurize.classifier.folds
    - featurize.classifier.max_depth
    - featurize.classifier.max_features
    - featurize.classifier.num_est
    - featurize.classifier.threads
    - featurize.dev.epochs
    - featurize.dev.features
    - featurize.dev.ngrams
    - featurize.dev.passes
    - featurize.dev.seed
    - featurize.dev.tags
    - featurize.other.dense
    - featurize.requests.num_est
    - featurize.requests.sample
    - featurize.requests.threads
    - featurize.rf.layers
    - featurize.rf.learning_rate
    - featurize.rf.max_features
    - featurize.rf.min_features
    - featurize.rf.passes
    - featurize.rf.random_state
    - featurize.rf.tags
    - featurize.rf.weight_factor
    - featurize.selection.columns
    - featurize.selection.passes
    - featurize.selection.threads
    outs:
    - users-train-feats.csv
  train:
    cmd: python train.py users-train-feats.csv model.json
    deps:
    - train.py
    - users-train-feats.csv
    params:
    - model.batch.epochs
    - model.batch.layers
    - model.batch.num_est
    - model.batch.random_state
    - model.batch.seed
    - model.batch.threads
    - model.batch.trees
    - model.batch.weight_factor
    - model.classifier.batch_size
    - model.classifier.columns
    - model.classifier.max_depth
    - model.classifier.min_features
    - model.classifier.sample
    - model.classifier.seed
    - model.classifier.split
    - model.classifier.threads
    - model.classifier.weight_factor
    - model.dev.columns
    - model.dev.max_depth
    - model.dev.passes
    - model.dev.sample
    - model.dev.trees
    - model.other.seed
    - model.requests.dense
    - model.requests.epochs
    - model.requests.seed
    - model.requests.trees
    - model.rf.estimators
    - model.rf.features
    - model.rf.folds
    - model.rf.learning_rate
    - model.rf.max_depth
    - model.rf.num_est
    - model.rf.sample
    - model.rf.weight_factor
    - model.selection.folds
    - model.selection.layers
    - model.selection.num_est
    - model.selection.passes
    - model.selection.sample
    - preprocessing.batch.dense
    - preprocessing.batch.folds
    - preprocessing.batch.random_state
    - preprocessing.batch.weight_factor
    - preprocessing.classifier.learning_rate
    - preprocessing.classifier.min_features
    - preprocessing.classifier.trees
    - preprocessing.classifier.weight_factor
    - preprocessing.dev.columns
    - preprocessing.dev.dense
    - preprocessing.dev.folds
    - preprocessing.dev.random_state
    - preprocessing.dev.tags
    - preprocessing.dev.threads
    - preprocessing.dev.trees
    - preprocessing.other.epochs
    - preprocessing.other.folds
    - preprocessing.other.learning_rate
    - preprocessing.other.max_depth
    - preprocessing.other.max_features
    - preprocessing.other.ngrams
    - preprocessing.other.passes
    - preprocessing.requests.epochs
    - preprocessing.rf.drop
    - preprocessing.rf.folds
    - preprocessing.rf.ngrams
    - preprocessing.rf.num_est
    - preprocessing.rf.passes
    - preprocessing.rf.random_state
    - preprocessing.rf.sample
    - preprocessing.rf.threads
    - preprocessing.rf.trees
    - preprocessing.selection.drop
    - preprocessing.selection.epochs
    - preprocessing.selection.learning_rate
    - preprocessing.selection.random_state
    - settings.batch.columns
    - settings.batch.dense
    - settings.batch.estimators
    - settings.batch.ngrams
    - settings.classifier.columns
    - settings.classifier.dense
    - settings.classifier.epochs
    - settings.classifier.estimators
    - settings.classifier.min_features
    - settings.classifier.ngrams
    - settings.dev.batch_size
    - settings.dev.max_depth
    - settings.dev.seed
    - settings.other.columns
    - settings.other.epochs
    - settings.other.estimators
    - settings.other.max_features
    - settings.other.weight_factor
    - settings.requests.min_features
    - settings.requests.threads
    - settings.requests.trees
    - settings.rf.batch_size
    - settings.rf.epochs
    - settings.rf.tags
    - settings.rf.trees
    - settings.selection.estimators
    - settings.selection.folds
    - settings.selection.layers
    - settings.selection.seed
    - settings.selection.threads
    - validation.batch.drop
    - validation.batch.threads
    - validation.classifier.max_features
    - validation.classifier.split
    - validation.classifier.tags
    - validation.dev.batch_size
    - validation.dev.folds
    - validation.dev.passes
    - validation.dev.sample
    - validation.dev.split
    - validation.dev.tags
    - validation.dev.trees
    - validation.other.estimators
    - validation.other.features
    - validation.other.layers
    - validation.other.split
    - validation.other.tags
    - validation.requests.estimators
    - validation.requests.layers
    - validation.requests.ngrams
    - validation.requests.num_est
    - validation.requests.trees
    - validation.requests.weight_factor
    - validation.rf.estimators
    - validation.rf.max_depth
    - validation.rf.min_split
    - validation.selection.estimators
    - validation.selection.folds
    - validation.selection.min_split
    - validation.selection.num_est
    - validation.selection.passes
    - validation.selection.tags
    - validation.selection.weight_factor
    - variables.batch.batch_size
    - variables.batch.epochs
    - variables.batch.learning_rate
    - variables.batch.split
    - variables.batch.tags
    - variables.batch.threads
    - variables.batch.weight_factor
    - variables.classifier.columns
    - variables.classifier.estimators
    - variables.classifier.features
    - variables.classifier.layers
    - variables.classifier.min_split
    - variables.classifier.random_state
    - variables.classifier.sample
    - variables.classifier.seed
    - variables.classifier.split
    - variables.classifier.threads
    - variables.dev.batch_size
    - variables.dev.epochs
    - variables.dev.max_features
    - variables.dev.min_split
    - variables.dev.passes
    - variables.dev.tags
    - variables.other.epochs
    - variables.other.features
    - variables.other.layers
    - variables.requests.dense
    - variables.requests.folds
    - variables.requests.learning_rate
    - variables.requests.min_split
    - variables.requests.passes
    - variables.rf.min_features
    - variables.rf.seed
    - variables.rf.threads
    - variables.rf.trees
    - variables.selection.columns
    - variables.selection.learning_rate
    - variables.selection.max_depth
    - variables.selection.num_est
    - variables.selection.seed
    - variables.selection.threads
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json users-test.csv
    deps:
    - evaluate.py
    - model.json
    - users-test.csv
    metrics:
    - metrics.json:
        cache: false
