variables:
  other:
    epochs: 87
    layers: 5
    features: 4850
  selection:
    max_depth: 9
    num_est: 181
    learning_rate: 0.09823
    columns: 89
    seed: 808780000
    threads: 2
  rf:
    trees: 3
    threads: 6
    min_features: 2738
    seed: 864241000
  batch:
    threads: 2
    split: 0.2
    weight_factor: 0.3
    batch_size: 569
    tags: 30
    learning_rate: 0.09
    epochs: 70
  requests:
    dense: 100
    learning_rate: 0.1
    passes: 11
    min_split: 49
    folds: 11
  classifier:
    estimators: 205
    seed: 439035188
    threads: 4
    columns: 78
    layers: 2
    split: 0.4
    min_split: 25
    features: 3878
    random_state: 124800574
    sample: 0.25
  dev:
    batch_size: 1011
    passes: 23
    tags: 35
    min_split: 32
    max_features: 3278
    epochs: 30
preprocessing:
  batch:
    weight_factor: 0.3
    dense: 300
    folds: 9
    random_state: 113828301
  selection:
    learning_rate: 0.05
    random_state: 183000000
    drop: 0.12168
    epochs: 44
  other:
    epochs: 51
    folds: 13
    learning_rate: 0.17957
    passes: 40
    ngrams: 4
    max_depth: 12
    max_features: 150
  rf:
    threads: 5
    num_est: 157
    folds: 3
    sample: 0.47593
    ngrams: 4
    trees: 66
    passes: 44
    drop: 0.33493
    random_state: 395000000
  dev:
    columns: 15
    tags: 42
    random_state: 681000000
    dense: 100
    threads: 5
    folds: 9
    trees: 54
  classifier:
    weight_factor: 0.1
    learning_rate: 0.15
    min_features: 3100
    trees: 18
  requests:
    epochs: 20
validation:
  dev:
    sample: 0.5
    batch_size: 512
    tags: 61
    trees: 30
    split: 0.07635
    passes: 86
    folds: 2
  requests:
    ngrams: 5
    num_est: 271
    layers: 4
    weight_factor: 0.3
    estimators: 58
    trees: 78
  selection:
    folds: 9
    tags: 56
    min_split: 78
    weight_factor: 0.10642
    estimators: 45
    num_est: 250
    passes: 55
  other:
    layers: 3
    split: 0.4
    tags: 81
    estimators: 27
    features: 4759
  rf:
    max_depth: 24
    estimators: 245
    min_split: 64
  classifier:
    split: 0.49728
    max_features: 1288
    tags: 143
  batch:
    drop: 0.2
    threads: 18
settings:
  rf:
    tags: 70
    batch_size: 48
    trees: 13
    epochs: 70
  requests:
    min_features: 97
    trees: 21
    threads: 27
  classifier:
    min_features: 1700
    ngrams: 4
    dense: 231
    columns: 31
    epochs: 20
    estimators: 179
  selection:
    layers: 3
    estimators: 138
    seed: 161839442
    folds: 3
    threads: 15
  other:
    epochs: 15
    weight_factor: 0.20869
    estimators: 238
    columns: 70
    max_features: 3600
  batch:
    estimators: 97
    ngrams: 7
    columns: 21
    dense: 500
  dev:
    max_depth: 27
    batch_size: 720
    seed: 821966000
model:
  batch:
    layers: 4
    trees: 29
    num_est: 125
    seed: 682172675
    epochs: 50
    threads: 22
    weight_factor: 0.20535
    random_state: 108227155
  selection:
    passes: 19
    layers: 2
    folds: 5
    sample: 0.5
    num_est: 175
  requests:
    seed: 61678532
    epochs: 71
    dense: 400
    trees: 66
  rf:
    num_est: 217
    max_depth: 28
    sample: 0.75407
    learning_rate: 0.05
    folds: 10
    estimators: 145
    weight_factor: 0.3
    features: 3110
  classifier:
    columns: 39
    sample: 0.66847
    weight_factor: 0.17422
    split: 0.5
    threads: 1
    max_depth: 32
    min_features: 55
    batch_size: 310
    seed: 667169000
  other:
    seed: 883404000
  dev:
    sample: 0.27687
    max_depth: 16
    trees: 60
    passes: 4
    columns: 9
prepare:
  batch:
    learning_rate: 0.12647
    ngrams: 5
    min_split: 14
    features: 1435
    split: 0.17261
  rf:
    num_est: 40
    passes: 85
    layers: 6
    epochs: 71
    columns: 6
    random_state: 895866686
  requests:
    split: 0.23405
    folds: 14
    features: 2107
  dev:
    columns: 43
    seed: 437495282
    weight_factor: 0.22765
    sample: 0.57073
    epochs: 97
    trees: 12
    batch_size: 797
    features: 2577
    max_features: 3825
    tags: 56
  classifier:
    columns: 61
    split: 0.18088
    features: 6016
  other:
    num_est: 238
    features: 249
    drop: 0.24525
    epochs: 72
    folds: 7
    ngrams: 4
  selection:
    split: 0.15413
    layers: 1
    ngrams: 5
    seed: 148068949
    features: 1582
    passes: 60
featurize:
  classifier:
    threads: 22
    folds: 14
    num_est: 95
    max_depth: 15
    batch_size: 853
    max_features: 4656
  dev:
    epochs: 54
    ngrams: 7
    tags: 96
    features: 2484
    passes: 81
    seed: 556576566
  batch:
    batch_size: 685
    threads: 23
    weight_factor: 0.17438
    max_features: 4080
  requests:
    sample: 0.21149
    num_est: 177
    threads: 1
  selection:
    columns: 12
    passes: 35
    threads: 15
  rf:
    passes: 17
    weight_factor: 0.22549
    max_features: 1246
    tags: 146
    random_state: 498815508
    min_features: 2049
    learning_rate: 0.07917
    layers: 2
  other:
    dense: 95
