variables:
  other:
    epochs: 80
    layers: 5
    features: 4850
  selection:
    max_depth: 12
    num_est: 181
    learning_rate: 0.12
    columns: 72
    seed: 808780000
    threads: 2
  rf:
    trees: 3
    threads: 6
    min_features: 2738
    seed: 864241000
  batch:
    threads: 2
    split: 0.2
    weight_factor: 0.3
    batch_size: 569
    tags: 30
    learning_rate: 0.09
    epochs: 70
  requests:
    dense: 100
    learning_rate: 0.1
    passes: 11
    min_split: 49
    folds: 11
  classifier:
    estimators: 205
    seed: 439035188
    threads: 4
    columns: 78
    layers: 2
    split: 0.4
    min_split: 25
    features: 3950
    random_state: 124800574
    sample: 0.25
  dev:
    batch_size: 787
    passes: 24
    tags: 35
    min_split: 32
    max_features: 3278
    epochs: 30
preprocessing:
  batch:
    weight_factor: 0.3
    dense: 300
    folds: 9
    random_state: 113828301
  selection:
    learning_rate: 0.05
    random_state: 183000000
    drop: 0.12168
    epochs: 44
  other:
    epochs: 51
    folds: 11
    learning_rate: 0.17957
    passes: 40
    ngrams: 4
    max_depth: 12
    max_features: 150
  rf:
    threads: 6
    num_est: 157
    folds: 3
    sample: 0.5
    ngrams: 4
    trees: 66
    passes: 44
    drop: 0.33493
    random_state: 395000000
  dev:
    columns: 15
    tags: 42
    random_state: 681000000
    dense: 100
    threads: 5
    folds: 9
    trees: 54
  classifier:
    weight_factor: 0.1
    learning_rate: 0.15
    min_features: 3100
    trees: 18
  requests:
    epochs: 20
validation:
  dev:
    sample: 0.5
    batch_size: 512
    tags: 61
    trees: 30
    split: 0.07635
    passes: 86
    folds: 2
  requests:
    ngrams: 5
    num_est: 271
    layers: 4
    weight_factor: 0.3
    estimators: 58
    trees: 78
  selection:
    folds: 9
    tags: 56
    min_split: 78
    weight_factor: 0.10804
    estimators: 45
    num_est: 250
    passes: 56
  other:
    layers: 3
    split: 0.4
    tags: 81
    estimators: 27
    features: 4759
  rf:
    max_depth: 24
    estimators: 245
    min_split: 64
  classifier:
    split: 0.4
    max_features: 1250
    tags: 102
  batch:
    drop: 0.2
    threads: 18
settings:
  rf:
    tags: 70
    batch_size: 48
    trees: 10
    epochs: 70
  requests:
    min_features: 97
    trees: 17
    threads: 35
  classifier:
    min_features: 1700
    ngrams: 4
    dense: 231
    columns: 31
    epochs: 20
    estimators: 179
  selection:
    layers: 4
    estimators: 138
    seed: 161839442
    folds: 3
    threads: 15
  other:
    epochs: 15
    weight_factor: 0.2
    estimators: 238
    columns: 70
    max_features: 3600
  batch:
    estimators: 97
    ngrams: 8
    columns: 21
    dense: 500
  dev:
    max_depth: 28
    batch_size: 720
    seed: 821966000
model:
  batch:
    layers: 4
    trees: 24
    num_est: 125
    seed: 682172675
    epochs: 50
    threads: 22
    weight_factor: 0.20535
    random_state: 92000000
  selection:
    passes: 19
    layers: 2
    folds: 5
    sample: 0.5
    num_est: 175
  requests:
    seed: 61678532
    epochs: 71
    dense: 400
    trees: 78
  rf:
    num_est: 254
    max_depth: 28
    sample: 0.75407
    learning_rate: 0.05
    folds: 10
    estimators: 145
    weight_factor: 0.3
    features: 3110
  classifier:
    columns: 39
    sample: 0.66847
    weight_factor: 0.2
    split: 0.5
    threads: 2
    max_depth: 32
    min_features: 39
    batch_size: 272
    seed: 667169000
  other:
    seed: 883404000
  dev:
    sample: 0.27687
    max_depth: 16
    trees: 60
    passes: 4
    columns: 9
prepare:
  batch:
    learning_rate: 0.18378
    ngrams: 7
    min_split: 14
    features: 1536
    split: 0.21976
  rf:
    num_est: 45
    passes: 85
    layers: 5
    epochs: 80
    columns: 6
    random_state: 956362358
  requests:
    split: 0.23611
    folds: 12
    features: 2432
  dev:
    columns: 67
    seed: 328752808
    weight_factor: 0.15615
    sample: 0.42957
    epochs: 79
    trees: 9
    batch_size: 936
    features: 3034
    max_features: 5295
    tags: 51
  classifier:
    columns: 66
    split: 0.18786
    features: 5840
  other:
    num_est: 238
    features: 273
    drop: 0.24222
    epochs: 80
    folds: 9
    ngrams: 4
  selection:
    split: 0.15413
    layers: 1
    ngrams: 5
    seed: 136815760
    features: 1427
    passes: 50
featurize:
  classifier:
    threads: 22
    folds: 14
    num_est: 99
    max_depth: 15
    batch_size: 853
    max_features: 4656
  dev:
    epochs: 54
    ngrams: 6
    tags: 98
    features: 2638
    passes: 65
    seed: 496152743
  batch:
    batch_size: 840
    threads: 25
    weight_factor: 0.17438
    max_features: 4080
  requests:
    sample: 0.21149
    num_est: 207
    threads: 1
  selection:
    columns: 12
    passes: 35
    threads: 14
  rf:
    passes: 17
    weight_factor: 0.2657
    max_features: 1254
    tags: 113
    random_state: 577915224
    min_features: 2256
    learning_rate: 0.07917
    layers: 2
  other:
    dense: 88
